apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Y5ihOZAPRjgvL7tN+XLfKB0nSIseyqvNIM8U4ulD5bzNgJ9Cpqch9Wb3S6pitUvk02qPZcHeYv9M5Lv+EqAtQxnvqAdJzfedozD6/ZosLKiIG+cbYFFpPxf4dMfvwna7Q/97rICm/MsYzBN/Wm4xRcklQfBOrtDbmIgO7uV9G9KboErW2yHm+JWmLTRVPg6WWI50u6MRY4zF9hGzQUMmuY6rhhHPvmJ5YzhUjh+XKxwt0kTdclyipJdNozJcCvY0kpiPfo5OVjmaBIKhgKjesSqBZe3ucgQ8T8eLhdukxU/PlHjrek5hMGHqSm4JyBNU5jwFNd8ZvifcTdNRmWDYTgOlb3w49TNtS+j+hIAAS6jLL+v4ujwVeUTvWKQYyZpi,iv:C/AzUYpbb+qty9Stl/5mj6I8QfLZoXObNFLi2/pFdkw=,tag:N7yaba3xOFWiir5gF0qz/A==,type:str]
    identity.pub: ENC[AES256_GCM,data:bILr/S3MY2kh0WbYipAtlXOAljWmMYxc7p6axnJdad0mqSDCiDW7zt5XnsOkEANjxhjJrZPAW+bN3LT/NN+6ckciJmQY+iTUnpMHccsWPzvb0qXe/ZPQ9+BC3uoit/wrLSjXjVONnFK1vQa9biqRUPxA8sQyNvdM9MJxrCCtrvizig1P9OOPqTl877VdSTL2lC8MmiDLDRhyxeZrCAA2TzDrAMp5GBltTR2UjfrikZwvB1RDL4uArb0zxIhkwq6VmexwaqQl2FoioxYBMw==,iv:1khf0UqQi+bdxYWflFdm4ztcMKBLCmkkGwC8KiR9L5o=,tag:6qxVvnY3+AAlZjA4nABTSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/81H05rZODvH6dvHteJkNj0bpYrg/O2a13vA5lRnqwmCE555XE9j/gnk+bNjqNesJEwtRcBrkMBAmiijqOoF5lswqDdKHYlS83PsqcwjnrhFxcS1AMduHdVskeY442IyA2o5up/Yb3auEZi1tttMLNNgtkPc+m2J6L55BFkXcs3lLDRYyzERtE32kUtGG+bhY9vYO2feUgQ6L4g8EE487OquYFMR2dVcBZKI,iv:AM9PK/+eeHtHh7/uUn/Xfg3byiRrNnTZTZPh8sgXank=,tag:dcBggc/fiSoWYeYOdsq6eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcy9JOG10SWhDOGw3WjI2
            YldQM2dySG0yZURrem5jc01LbXY1R09oWDNzCklFTzJNWWpzNmVVUHpJWmVuaW1n
            Z2krbGFxM056R3RCZVl0SnNuN2p6QUUKLS0tIFp3MnpnYXdXWU9pVjFrd095TXEx
            RU1NRUEybUI1anF5aEwyUXhoVTNWY3MKXYAnJ7iB9nS6F8IzcKNc7zKKkyrN8/bv
            5m3L4SMkPlxh9A+Rg1jSRjbszE4KX4uol5CjOEUNBUPtYs9ZXFv5WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:41:50Z"
    mac: ENC[AES256_GCM,data:AS866kCKn2ljza/6x2CS0D7fCL/9CTuAtauXVD38inJ4D/jDtxM1jj4iggqZ+8Vqu1nymyX0XNDk/bMX/Fv0MKeZ7py2Nf0H2wmgLXB5WJ6Q7IA3SV96EUrZXiFmEH5tgDAdNAFqm3DYV7AYjyVRxX/YxCdaTbQ7zbM2vqn3n5c=,iv:vYligxfnSIh3dAJv+hC6Zk47V5Ek0A0JNllFm3JFYyw=,tag:/wCKhu8pXyy20C4XRSanxQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
