apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VM8hm/GUXjIfajUgFGRlaFwSKgpWNEV9BvjgvxOIE8k4ApwZYJacSDLlx6GrePnxUzi7w0hOGp4KTQlUe1BTnDUhGYEthQuzDksvjMagp3AyUtKIi7ruXoLv99ZnlR3BMKFL8BJNfhOUcH+Ry6flxjt/o362voPI8hOFh1XlCX6SsSTb9r/YPEUlFRPTUm6TT2XWR0LzD43zL8Rc/nJ19cPYe7XvbvI7vrvKc9Rs8u0qgFztc3RWXAXzjF6ICpPLdeOlgngdhSKW7aHEpjKiVTrDyDzxQ/5xvWrrtx98uMw9+sQJMelE90DwmUDtwjuS9mAbT4YadcgyNkbwLzucm4CI2wUqikeW//cLIZaX0cd/cpGtdbZLxZhoxKzX6bZW,iv:X1rLquLDQ2YmPQXnsUZdCkn/SvN0bskBDV6049txWD4=,tag:RjK6GHtGz0D4OgVIU/zlPg==,type:str]
    identity.pub: ENC[AES256_GCM,data:j6V4KI9oIu2N/hw6QshQyM9ghz8brJuGALsyzjyj5FiHgnQK12vgJxlo0ZnkxcS+rE/B6gyLP+1/ouoqJ5KSknC9nfoxi+eqpAy2LV3c86JDuAUH+/EwJlymBjdM5z6Kun4yk4XGUN6rEKUL117gVnoTMJRHjiMmyLZx/Z9K0ecdCJ6spj9fDnrvMZ45umO881wWPUP6hA6Wg/ZEvAenq/inJYB+5lGib8SoBScI8ddpU61w6GxSwxVrg/yKwfGp56TMjHSVEA9HKsSryA==,iv:nIjZ403tbxC8VUq0/4WSwTh6kYcXrinbe25IdqQg9MU=,tag:iCfkTH4KlC+259+UYSAQRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:zsaQzrJQH7O5Ch3eETNcgBhr2+p9zCWGGQMXiYQw2NsifmPdt5XqZ/ndGw/RbxA8J39Mxc2Xa5SCVtdEJb1+/QuIbqJVvc1f6TIS5C4bQI3igY5vZS4nQJUpApz4ed/0jIsca4oQ28YQRldU7BMl+j5tVUef7UCx6AQlMZPmaqS5eucjiwIPFlJkCq2bK57bpk3/wwDreOTCQq9+yhFiPpaiIxWrrl8pM+1I,iv:wO5tEtDgHilgT6Ek9BWz87D2GYR/6D8ete1wcfECw3Y=,tag:p3m+nyjZTA1PmZfDqkWBFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMjVyNUxocVpMeVdHUTZX
            SVRxbm5RaUxjRUFaOFZNbmJScEZUTXRRWEZvCkUvODZBbStVNzUwT1hjSnUwRUVh
            KzFpWHNxbTVlcFRNV01hVWtrZk1EaGcKLS0tIGtHeXdERnhjZncvV2VkSjQ3aW4z
            cGtZWnQ0OVcwNzFaMlcrbFhTMytyeHMKsvndDTTcwZgeHiD+ZsXoc21+nGPoliv9
            hE4i4jqjr0VLIQmxOOZ1gkiQu28gHliFJhymCCj7vVGvIIzcfDNvFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T14:24:28Z"
    mac: ENC[AES256_GCM,data:RUZPSjcUZf5OaJS8b1IvUlbTr65MLHxRXJrQcGWvuK4QtW55lBf6UCLubHuYx1F6ne1tZxjL4RpRcoTmbYjMbex7SvQmRApmhzs7mz4MYpTZ13tn4ZZX1rnghGV8gTDBKlP3T5TE+T48+ndtKrJ8U8ycXBWrUgoDRk5RNfh+aEM=,iv:I8NytAKakRaPu/X+mhnS+I9n7sv/RmmddSNlJCuNcxM=,tag:m6HupR1MtG2pqOeg5jg28Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
