apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ghIRiC4mzDpWNH4t2j0MI7IHqin+uATaHuiDJjjHFcPWBZ1djS+9ZJL8Zn907pmR8JNXAc9KIKuwWfCtxEFJVWSrfsmpEhC6mDRFolmegPTyDYV42fZriYJPs2wY+S54jjmase3uu1TSjDKVoUdSq5nvQOx7p0z1IwFrnB+sS0+G1zTqZU80tS2SoPd+fVay4yhk0kgt/SkDzJA//QvN6SXevEIqBR/hdO/uX+SOmfpOUm4Fy7y8ZcAzmuPRczWKdFnRpsMJt4yAZpQbJKCF4KvjiVGIfG4cRoVCjafT3JAABeE/8NfwJS21WKL6NNaU7sfOrKtVHcJ/ek9r10qPFjMEpQjJUXUD7jIxgJntfqzgLUwLgJZBCXprNNXFy/5x,iv:O5Scp5ql7aF95OgFqNd5PZNEUGjN989s6Fuz/SJF3NY=,tag:5HU2VPHK2wPfXqEiaJTCxQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:PJ9PE3bA8XrQzsXUXZ1gvwvLRt66msL8d2AL1eMHsymEKXQY0pkqpYvOMOKKP6LRRVOw1HPpvxW4APeueeM3Hxq4AKiJEvXkBaRh21n+kgeMz2KkHlJ6rAnj0qNCQpuJ/QETfYectrpD5iZY4q8z1zN3NEE9bTLFTkqHZ3Vm6+jTOhUd8uVr/t4NHa1c38Z0qkbASOUUmszWW2AW+effAp21yfxZCHGIRhtG6jSiczQ6QrUF0+zdWSCSP/nM/QhcsgdU+/rN1XA+wRnOVg==,iv:M73hdVdC6xom41m01eHKLclWFfJiSonims72SIYmQX0=,tag:VJfDbbIXLNR05EddOqrznA==,type:str]
    known_hosts: ENC[AES256_GCM,data:caJvMH9Z4xU9MUdasopcu4IQs9fWY/OyiCc4TY77YF/Y5L/rqyvFc71Omhieksw4XO0PQ90LA8LO/j+KJqQ4haBrUZUpRW0O3a9wSH8zYe+DLvJbLnCdQb3LcZG3ylWcg/6T4ek0BAiBL78amTMV3xC+f6dctgPJmiFfqhDybgwtpxHRaB6OQLs6VqUYGs+oM1+oOGuP8j3IqZOzDgWMdRSLF6xtddnMeC7+,iv:Vy5ckP6YzQ3eHXfY5uoenvG8RgO7mYYWM+n2xJ+biqI=,tag:ubPNb2IKwQiy3zGmwCieDQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjM3Zkpzcms2bzBDOERJ
            NFp3SUdtZlJSK2ovbWlDMGY2V1o2MGF0UkdVCmprdi9YYUgwd29wRFNWODhTd01j
            Wm14LzNHbmJobnZ1WUdsdWlDSGxURmcKLS0tIG1Cc3p0UVFXWVB1aTIrVUxoZmZV
            K3ZkdjF1YmwybFg0UXdvTG53enNjelEK3cuQFflxlc2+GwWhZDjQ8YJX42FQG2LK
            ecz9qbjXQi3Qy79X+xcGo5MtEyOLpnbf2UJ/HcJ6SKWQDjEqduucwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T18:53:29Z"
    mac: ENC[AES256_GCM,data:9eAkD7tn5hgKtmr51L9IEZiLi0AuZsdUcQUzb5BuqTlzaLqhmh6u1Ft9GLhjCprK2qurUPnL5ZUW7UoZfBwAIAGsE3McuOFIc0+UILN7ridm8svhjueQiB5oG/uRJ9cZ+FGO4mT6YFHN51fUuZZUBzowivAtvrZKzieSBgsrC5I=,iv:LeRultqb1NmUubWa71nWlrZCmUDsXjCIXW2nRqJTKwI=,tag:jqh5aPSECnF3Oro8RMTcmg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
