apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6W82tzVLhBtEHcVZoeCj+i0Z985xZ+HhDtWEqHRrmc+p1wV0GoWPxrVTThRxnfLaXzvdpBjnjnb/V2Vo+6QnMne5jjcpZ/wz6HheBoV/tHsHTleEoY4BQFrqrf2C5iu/V1ewujEZyypA0xVcjjy73jZ24j19xpOzDo6BD/vmqG6x1JmsT3h8v3DfNstzwuk/iDUEjT2YCYB5/g5C4vj47CuIZiKMhSkaY1pjws5yuysTXkpVtKTp7+SmwS2PbHczWcCpcI0xs3P0xDgokwbw6Gap4SU+R/WU49iDgknKk1pypm0jRqtNXFiCn9xTFYHejf9JfpLoF8Q909/bgIdJvo4KbB3KNJrCaNHp9SQs0tqSXNjKQENcWdGHSUmZXi5r,iv:JGUPYj6oHBgcymMgZcA1alGmXX0v/ABE0MX6SJ6R4kw=,tag:2gMOZkes6RekI+U9x5HlZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Kan/qMasU+l0g01H67/FhPz6XHMNgR56PNn4AmL3ApLLhpOqAxx0JMEFaS7TVtnHFskxSbyUSt7Tuv3i0ueXxoGX7v/FN35idultiSM0zs1pPBAVODIlS1XuBWNFe7Do5pFe6NEahFfb1cvBXj0BADjWcEpAmWHPqStWd8I+h7qp6JwWiUlLhfDEX3/hP0BSdal1g9XNP+lP2cHsjLxLvJxI+iqQe5tn3P0yIRsVMtERBdNhQ37Ej0qOTxN1Jm54U3lvjoShjoahpdZcMA==,iv:Tht71XM02RF0w153VSIVh6NXYaOMXWC3Sd5d/xPezIo=,tag:kGFf8DIKu/s4+IHYrJQwZg==,type:str]
    known_hosts: ENC[AES256_GCM,data:hJZRD3tqjcVyc3ao/bUJu5dho2fcI92WmklwS0JJwGMLCdnuRiBApgQhMKqwqB606QSsmBaAzeB2rc962ZdmwgRcGzKQAfPRGbTUt4NBqTc1opP0aDb7B4TjF9Moa2s/EU71irDBVj5p6wyW9dNnLfU7RLwCDI4H3JqOwF2DWLjYyBud2CmH17djwpT3kM5LZgiVIC/ZdMlNUXqgDL0IIVbUefuL4V5T/BSV,iv:zm5kp68Zx0Y0rLyyfN+omXyPH/TizVhpdu/qYVXzY1k=,tag:ECuKEM6mhbWNs63Xfjf4sA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5T29FWUVsMmlSYU9kcGhz
            Z2R5ekREVDRrYVI4biszNHNibytlVGtZM3dZClVWNW9UaFJFN0tKc2xvVUFFT2da
            bVRXSzB0OGdjUnJWcXcyRWZKMjB0ancKLS0tIGtUb3FBK2NOelZTVmRkTHFuL2hi
            ZnJuTkhMT3hMVFdMUHFIR1UvMkh0WlkKCgob+CGbQ1RfMxYfHxrN/WiJNRMVHKpb
            NfkXSBIxycRzSyQFM1TJeI2swrUokGO9Io42LOt0H8nTN6CdxFjp1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T13:47:43Z"
    mac: ENC[AES256_GCM,data:IYJC5e6/g03HVr0/P06RfeYu2Q21XE2PA78Le4UTNlaZAgAg++rvhCgMix+yWo8RJCjVfoqR6c6ctwYbndyS7GW8yE8JYJ4He8tuzkGPWqW/W0cRJGPIDNRdBqRcrt7qFXbjmc2ZLYyZkl2HJLYqHg8MeZOGVBantC1ceR67wPw=,iv:vwXkckzkxzjmOZ2uA/pK3ybc6uNmExPNjpLRDpzrOtQ=,tag:OPIgYFMoEGngq9CN80ruzw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
