apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Apn/bEvRuAU1UMHrXMGLbPHmUEVXMUknam4dEZfNQGZxJ4LdgDk+XLupL77+/gX47UmIvyQcxYw72oNLBp2DATw3qjgpa4LBqqq8KTp4FyAnjAH14Z+y5jVgZkf6u+TUg6iwlvEdfsHNuNPtmfMKs8dRmH5DUVe57FEP2uoGmnf6bSQ5id6yBhV1KnQaVBgQ+VQdduJ06+KA5ns7RRg7LYk/+QTY+BkhZb3UP5h+MjISNB3ULrK3ON+KvYv+SXJnYU7MVruwW2Q7uhn+iXxCH2ZF+cS0QhY6N+WIX/M8qm1doMq8JdwSI6uDdgquu41xhwD/yO+dbt9Qm7IjrioGdmBHs3UStgrnBwxS5ocmDHityGTBFaHEZgQXCN+5nmYl,iv:J08BOupH+oGL/5sggwgLrBoJq12fS42MTj1mW/zuOEQ=,tag:F4x4OrrHn8ckHkdII3faaA==,type:str]
    identity.pub: ENC[AES256_GCM,data:Kqla/E7HsyXB1Wj9nkao9gWjU8wtTjO9b7c2keL9uR6sie6mzQ5pSkYV7RfjwlsQan0t6ID27UTCwA2783uT/j6fJ4MQPD3lzLEEyx3Tdegtv4m0urscqMyBu1aSB7H/Kvblo/jtoXuX7Wt5GFgQSlq9PJvHslFM1Z6paou/Cwxkd7MRGJ0TeJdmp43CmJ0dN+8XKP9ke7FCtX0a5UwGSwhymA507pJnfZ0ZWvmAdJxvqOpC/Xs4nqgKUOAaU0g5uDBmpJ6foLe5oFAx8g==,iv:M4dBWXbi3/tBiaW2nasncVqqyUMLUToazpLQp1ni7W0=,tag:FdI4ktXEooSnOuv/6bwQzg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4Lz454ezfanJ18RYV6UQ+GoCkkdH/ClckI6uIB9VUtomt61DYJTMXgtEGdVIzIiCuaLLLnebiF7rfpHpuOA/WFPidGq6qOQVNuq6IskqJEsMZuk3oEiX0G/low9NoXHXs6jdFT3MDxROHZCRLQ75q8MwOBT/NnhOD/2jPW1MIOiBwziesm6IrrpKMVko13f0Xz03KP6eto8PflZcyNWH0lxICA3jCbb4f3z3,iv:7gPj7eA3XWi23ODbZXHx0iCEu0YIrZ4wxDQun23dApY=,tag:ZpoCuS2UXMlD416CuR1Zfg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVi9CdUdoVWJGcnpXQ2NC
            WDZkVE9zYk5EblNRaUYyNk1jVDFWOEVZcVFvCi95c0dqeG1WTUlVRjNTMnBTZDUr
            R1A0elJNNGNBOGFYZ0tZaXpEMkhRb2MKLS0tIE03N2RWdy9MdStMVkxNM2RZZnFS
            aC9wdHcyS0h1RDJ4aHp2b1ZJemRKK1kKAIECUsRxe5Hd/dIt5nma1c5AW6lzD1xp
            JKk6sp4AjY0ExfXXeQFVvbLmMdSURIiFH6yqoah+J5k4Nm91lRoR0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T20:25:44Z"
    mac: ENC[AES256_GCM,data:AfKtPmiXBflUvpmPyRiJnN8awur+yQ0fqLjvnFjd70srfbmA36FCGhQ3hdGGyqVFetZBjkGkwJYr1R8V1sYo83KLxjHc8e9Eoxa+u0GmTJzpjTS7A+0SBG8K2gaFzpnoTw+zyZ9D4VqlkN1hxa3pRWKzpWy28yKBbM/ie+4aOz4=,iv:Fxc5cbbuXx4T10KZrHJAgm3puCeF5woSBufSYkdEYtA=,tag:6u6hnKDXbggwxpEVVsA+HA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
