apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jFac0hawvcUJvJZ5/9YVKeEfrChLFQtAqXUBsNVAHWwkPwzs+T6ljm6Ng9x2W7Xpxfed6T8XB0fbV/Psn2tqfqIn56j30JNSr5wyG4hPpv3nprVUmh0Psp30tOrLmY3LpWvDSuP2XEe/Dc//7HEsR4A/OKi+BJxGXXc2IZksN5j7X4yrCMnB0FgBTPw9Oskx2SLdxvvfKF5vvIUXfHJ07qC+IN28W4Tdwn6qEp1kSHoVI/pRgVrAuXpM/8seBnqyLP08f/OztBncxPxc8d+S9+vzKECgKC+i/Yz+k0zNOM19v7vH3bfhYb08oFU98vga00hG3J3MGXrLD0Rr+QGLHybYzmg6+iXn6j0Dtr3UI6bbt+St4/puY4CXWzQYYNJ0,iv:BfRin+dbcUFBvHSGNAO3nlt+hpgt20ITStpvBZxNecg=,tag:nAdCpR/ZqGBHqVnwg4y9RQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aZiq+x8lhVhrsNKl0KRGN0Hq7dFDMq3cGpfRBBcxXLIjuWjAxjbcjN1YKjkbaXGW3qwPxws2RmN1j4u9ePIPXsHyjeBuCkChuoWCqMo2ItlscfJyxaUyubTK3yawDhr6TW0l7jPj/ahet0l9bdn4Q2vTTAVYBBUdhMR1VGONRjHZEiE1KkFV+ucRnYZwqoEzn+7rx8g06z5J34AIeUHz/k9QpqTHstxIJkEWxswRt1LZJnQL9h3pujZNm8yg9KNnphubjhck7NqqT6/d+g==,iv:vxxY841OHtXwlf8iIRXiJvb+avlo+zlTyFD1PSx78Ew=,tag:yDITZUHl9LubylOtRloqBw==,type:str]
    known_hosts: ENC[AES256_GCM,data:icOl4UyJXZzLi6mocyVAdB3UBFwUGNd0le3YZjc0ua8UgdxY71RQUmXKEVc15wwnybCqm6h8iiescchx9YToEsVY6V3h+b4nmqeM5CiBiMuJIVw9RYelKIcE7l5zbLiIpEhm4VR6EqHW88cHxbLaq1/f9fn9+BJE0U/bTzzUEsRYel2mThEnhFcNyKo18fRHsfqN8CTEWxI2S0zD5u9sDTI8+iXuiwNz649s,iv:Z/BC1W1MgYg/ajp6DO4dPdB0vd0moa3haRSrW+MqlCU=,tag:Ti95tWdl41GQaYFxbXVtnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNVBxNVR0U0pqZFFCN0hs
            WHVkY1VReUV5TjVXNGNveFVPWjUxUEFkVjNvCkRNMGpJdTJINXZ4T0huamM1TGdy
            TXNITkc4MlRlSDVoZGVQYkZZanBjYTAKLS0tIGlZb2l4NkpoMkdpZFMvTG5Pd2Yz
            dE1DNGRiN0RVVEd1OXNwWTN1cEpNNHMKUBCYz/KIvBlPSoberZgcr8mK9uLFlne2
            UVChbtS/Bx9+PBBAGTaG3fFjQeuzXm13mWgH3a/bWTkdGC8dDfEEDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T19:01:26Z"
    mac: ENC[AES256_GCM,data:ihI3xXH47JeDlchpyFJkWbgXuWmMA+k4zWmcf3OnscVU2St2DQxdIQhiwfcI5KKXr7VmvrhpROXi5M4msUi9+F/7J4mNhEaM9fHBRsJhMksIa/wqXa/KPleI+bNXNof19O5BWjv158MtofddhzGn6AWqX+oqvbW2l63Qv/75jC8=,iv:y38z7pn8QPpxwBYB5JsohXCmKz1PwclBrYzSdfo1WUw=,tag:yibWjw+X0qgKYHJHwYWvqg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
