apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ELbnsyTnvw5w/rZ+7gMMa9trFdEJQDa1yNLnh/FVBxh7GmmyNnrS89LwTJjPRmEWxxcKnw8vqSOTt2ThDCRVMTRxdbbLIDk5W7dXVyRBQmMRziTtfI1zGHCP7jCfhedTBikhUo5liPoaL1mUcU24rHi59ac+cjZYZdCbAGnACtSZgcS2WOi3faY2JnT1KHUqL1tKnWqCMw0QSeYx6/gQdU64DC75wtxBzWqLwTYqY3aj67WYoHBnplj3ajjj4lhPkN9I0doAJVbEk2+3rfkwxAARSF+wCub8RoUh8c6ONf9i2OFyfWHRO/qqygbRem+R7JtRo9Pb0epZA4Ao2BPTvm5s4leLWWAOZmdE01swoTlwhhZaY8ablPisf5cvRJTg,iv:x9gPQrXoIPQlBJOY6HUemNy5Fuo6QKgT9fixyWGt9ic=,tag:WUMeojGW4IEh8dvYCbKpEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:PR7B+ACARAuAuEI9m/atiu2nE0kBF0c+8NhH2OCzl6E+4uI0y3UggswYJ32tLW8Gl5l6+gA0+0O3+TEQzs3usNvr8HFWltYYfZgH+Q0TWklQQ+R4U3k+I/6u4VsIC4cEbgkjq8yc97RRwR/8K+OqX614pPJOjeLR0po5DXkuOf07/PB59x3xrA0ekb7mNs3OypCg40E/0ceAH0KOKsKJDnfpqrTLNjUEv+UcPUtaS+OlSzFRfi0inzSt1WURNLVoMVcdWxxe6mEwPzkTSw==,iv:5PYqYbxBanQJ9vin3acV3X2h48w9DpLWmzk7fb0lKVg=,tag:ntm5cGvV+V3Gm3fhFkqenw==,type:str]
    known_hosts: ENC[AES256_GCM,data:CGdVXeCgCKXz5oXz7A2WBCsmjNuCA/f/MskOqI7heCzZRhQuY59Q6816VCqxzSDm/e9dC9v1vdNgqUC1K8GlP6AGVTKED/xzlpKs+lBa9GORtMQ+PTcoUFRriDt61fOmr0vZTBGqZvUHlY17JhXZhZCAh0WVw4qlH8PSpoRx1sZhUWGGoYjm0deTrGVz4M0vfJD5YzX2YN3CA6ev2V/4IB5VhjdQZBKPstqm,iv:pYBrvNctE6yrm9KXnsSIvCP7bzq9oCJNjhRyJjhcw3c=,tag:mAMKbejbP1WexA66HQkJAw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbHd5TzdZTmVmZzFpdGFU
            d3dZTUdTODBaai9GNW0vL28wT0VpRFBxcW1BCmNkTzR3QllwV3FQQWkwcUMvZmI2
            ZXNZZXgvd3libFRiRUVQUFB6dkMvakUKLS0tIDZ5WWJBQSs4M3JpcW5JSThkYmUx
            eHhoa2RESGo3ZlpKMWZONW91RjUzU1EKgw+wpEG6YZtYCm66sfuBvERWdBdqGsuc
            sXmEhuHQnDfbSCS5Ubt7JNZD297kYUrK6K8n3aK+8p6ol7g88NjrQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:43:36Z"
    mac: ENC[AES256_GCM,data:i2Z4xFWB+ZAkLmy9Ex5VBs4CD52gDLsCnEr4+sHEtsR1/pPTenwAv14gE+AubZzh+mnmUqaymISTaTaDAsP2NZmdWzxEL/fKeHvIuUhylhqobv6GRk1SMDUIISI7yZNu3tI3sVsAN67l4PtCqQtB9bjYADXwlxLSztfPEZawfsk=,iv:FaJ0blBVnI+v1Q1Ovp/IQlRfd/NV2Y1doRbQkEfjJpQ=,tag:qcWwp9PjImKwBPzs4ZXGiA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
