apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UyAZ1hDQz3RmvKI9tA+oAtF79T3NFYnUPRyqnQ9QnVCdEIEiAUI0KzAqBuBELZSkwBhYFtNcmWttYNRmz4WPsRCS0g+3/QyaIguIdYx1k03vm9z8sUFcEb45fJEKMLiQ/OT+ljV2b1fU87F/Dg0oW2KSWT2LiZ/Xm+X7q8N9zpejiXlcpXFMzcP8ESKyEwXapEIfdThQ1+cqEFxGItXALhGLpruvuD7fTlScOeqD7l6A6mrrtJc/TKR2kCQeAYZpv9jMNYInAF1nmD1fEnmybrUz194qRmOaXMcm/b2UZiaMFKcwrjkRsHTlRi+VUug1dfS3Ow9LG0hFEFxdUSb0SdngW963A/Asm/SbYhoSnQq71KViLSGHDL6ujzSEgfw3,iv:niju2AWssyrp6MXYzI+Y96Kiep9QpPnYY4k8BmnqgPI=,tag:KBpV82r+Zy9HbfdyArz1+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:3G+Ms/F0XjXh/SKn73iEiHaXEk0XvpMHzbBv+PJk+immGohzIHFcAQW61yzgjowkW2GDkw05wJefvd4B5Wmll3SYrA+UE5Q5fm1uK17oYAqNqCp224zwWgcmPBMEay4BfbfYohK7A86icGF/hNIGBqecNV4KVS8a54BJaQ7OYlHrmJ5DL8qMm22QeHtqjja+0Es6nXUzel7GD1VHvRnrRTxBG37TaY7K8RwX+lCkf0BUbP9Novf2SZwpw6K/r1zBi+lq0XV20ZaKxHpfag==,iv:wNKruJSSGvXclidtb7ted1lonQioCiUPDFalsSvyuMk=,tag:y/G4Qk2l6kLWiOuUutndUg==,type:str]
    known_hosts: ENC[AES256_GCM,data:XN365SJk18CkiYHhFuVVvjzTh12VJrDb7l/zndgGr8TqY7EbJgF1YYU+pbSTzZubR8Ota2UVjz8L3AUGa/MS4Qrx/2N5PW0ZVZdCCzEwNHe6APQG1CiQOo8fCmyYOf0+W7dXaSvm1qUKKmVzL0KjEhqSpFpAeyaTSzavaUYYVpfxpQbBL+IlIYXqwpRKJXvguBYSj3loV/YlvzuSNVH0vII7l2EnxfQOTAux,iv:mZaP/75gPeER3UMc8uUhAyniBWvlzysPxT8N9mQ4puE=,tag:osBy+fhnXwR+zbLj8q9t0g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2h3eks0b0paUm9QcEdQ
            K014Z2w4QitTUXNTSjlDZFRrSVVselZEQTBzClZyUGxDVEc4L2htb2Q0MnF5dU5z
            cE5uZ01rc2M4TXEwM3dIMmt6aS9pNGsKLS0tIHUxSVJxMUZjRUlibEt3K0FtVTAz
            eW9kcCtqMXdpaEtxdEdMTDJ6ck9VNlkKSBOBghEtK/E5gLkLarLyoSVt74WjIZPU
            b3eINnm+nXsN+T50iQ0rvBinlI67IUy52czzdMJcjBScLxJHzcXXnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T11:49:24Z"
    mac: ENC[AES256_GCM,data:V4fEDNSisyrkc/BOZ761k0xdtAVcfa4OmvBi7tAAQdPP/DoDl71EysAN9524zDto6uTH7JIeAxe8zsWZGMOvI6jM+j/ZbH77Gp5u905CeGPMp8HQFEEaKojZVQ2k0+2AEDe3scR+7vh01kjaXwc4Lih1Vvk5d6itVS1vJHjjBYs=,iv:xxgSfmYN+Sd3CaIjJRGCte+lxdnGYQd+wo62UzoGoOo=,tag:ZPmvz5+JRBjMELeDTxHJXA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
