apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:81uhy7fy3LRow2kt6POuM0aHKsQsAyyPROR1SRRvJlg4ZtnAOHtQ3tDI22JX3p6fEopm71/+1fDX6G970TePUpVtOnZ/hz5btKDTofrhCacmrZzfpXFwFzkETCX85uIUupR5l/LtPmsONQCojGYCwXLd9bvEkdVRP5lSJqVyZhidFt3P42tO5vDbxarN+5WXUJn0iDEwXRuSLYVrJTX3wVzXL3KWJp06yKdUJ7BIOuijBCxjLspAbzCFwr+HzQQuo/X1JiGP2ovTFLInE1xf607Uf4LAiiqYu5+v4IQVRDQlhEGbvLeY7U8SF4GMKH7Y8YNPEbxdHBJfT2roh5MhtQvH7aSmwHDQnMcoh/wp3uY6eh/AUKiAZkAIBui8RVoI,iv:dFBcgdTKHgXnBnafKPKx+ETrMyAAaPfv+yzE9R+g+x8=,tag:0AS6gufn8iY5MDjmirNERg==,type:str]
    identity.pub: ENC[AES256_GCM,data:eMdvbkqrTrE5easVSC7owncZK8j7kHEF4C37n+ubMeONGAyaWGC4bXhOmdWtBA1TWtvcgkJhDA/pfiXDZ7z9wUmVQJAsP87R/6zOHotZ7T+AoZcAUJexaIJ2nLnJz1ic0v6QUevba8i+NcRKsPdGG5Jb6EGaLpw83kU+HCLpfdDEmNrBOL8JSkohiJum+9FQaeg3K0rXYAybE6mJI9w/Wg/IdtG2uXMnwsqmf+bHX+dWbD597gOSmnvSbzyPzb9nZ07isWXoeu9twg1kJQ==,iv:riMnMdBJLi7SBL4Yj1VirL9vkMUVFgikZmgbpWhEryo=,tag:w+eSSZvFi00D/GFJooT/rw==,type:str]
    known_hosts: ENC[AES256_GCM,data:g2QZXVTS+WJHVMph/r5yXZSnQvWgC1Icfw4SbPAxXkjSb6jKm8I+JtllKtlV9xuIrTL5hhS8NdtoGVW6/lM3ARV4dnGSO6z8N+5Zy3PHs1XOOEYioouiM+iJhMYw36pdKRDpFHF4egDnF0FZ0fBWVP3y9AeN+zNP1Q+i+7kGN4S4/dlWRXgqtNL4nRTyrIWb6K1hUE6tu5dbFDpL5oszv7ohTs4ls7/1ag7r,iv:8pGPAwrbUzXGQl+rA4hNLVkYUEKiG2w11kOf5SrjZxE=,tag:19s7F7PR0o3kMm9eFJzrMA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cXJNdVI0c3dDRXppaC9y
            WCtac2FZaGExY2hWM3UyNWdjRzFUMTZIeWdrCjYvbHJUYXZLK1pIUnZCN2hPbW0x
            cWhpQVVUK1VwZWx6SncrZkVuOS9ZZzQKLS0tIEpucTgwWjlUcnZ3ZE9KNlZxb3c4
            Y0ROeTR5cm1pUzdZM1hwNGVYdmNTcDQKnrgQGN1HdLSA9Pcvd45meIUrTLXvtGKH
            48ekMF6qCSoRbnwk2Dk52hlYHknKIjYpC6dN1+vFAeUrH+Cuihy6lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:14:15Z"
    mac: ENC[AES256_GCM,data:xBJUrmkxiI1jkaCJcDTONadNyYFR7qR//HS9Vwe/I90cMZgm1nfIK+o6RQkKzr61NkVvFOFb9QIdEEfX08A6cEITPds2gmEjQGMC1Fzdi7hloCNgrEZ+/POrU1P+tpFViKl7R5gPuw6wCUWmLz2TKTkAIq3QWlwSl+sJYpFNEfI=,iv:cqRyU9X8rYE34pOaZganPVX4Wqg0MxfPJhnEotDWK7g=,tag:kGplHV2RWGsAt8YBzAgOhA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
