apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PylHR2HR49XVS3CpIvBh1JKzUIwgxU3ShkGmSpLvZLyAiFVpgiZRZujiK+3g7JbOFsvJBKPjGGFd4HLyGs+1cP70qtPP+AEPjRBY481Pe/u6Go63DYDJCXi06Y1dcW4GGTdfVGi+shWzUHTkJiht1/wFex9gxLTMuFoK0wBr/alG6LeFVIjdED6njU1mLp3vjaJfMRHu6BWY/Wh/H450eA1ARJ3yxzDYbIPKsjOaqc618O/ippyllldIr8HuDRfLmU+TWogfXCjQLKo4I01woZ20OvKC0wVT25M1bdUT1w3q5L8c8cRJ3YAsJ3M5UljAiravoLCk5syOVuLXwsXq81kQl4qvDmHVkVF0GxsyokLrS+feG9lgPhxbMJRMMnRg,iv:UFV8d9yGPg6QwR9Mk96BIkLE6ylw/64qtVhahOthkLU=,tag:xT+leDr1PWh99SDoXamyGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:M9lBFr3tNWs+GO60uf5WmOynWxQzv7Xs5F7eI6JqzVVX2qNpIZtt344y/X1URZPGkMm9VXJiHaj+B4VjtKP1NSzuPu29KoVJFyC3m1gdJd2V0frJUW5oIc90MECZ1HWrTbj0Q4e+rqdxAhhhuV50f9c8nnR40PnAAH7atUgy/Prjij7mJwRDIgtQMiKyaJsUDZF5Yw1BJxKsH2acO3C2bZAb8p0mVKSNFEbKOU2wtHCS1gr3wwRNHLI5ac2qV1euaw37NcQ2/0Ntsl6fnw==,iv:zMLI5oVXf9A+axuPOO0ZMpF6gSxa3Aofd+IBrxplroI=,tag:HNXfM/QpNcNjccXwsjZ21g==,type:str]
    known_hosts: ENC[AES256_GCM,data:uodtQdN27LHE/1eSz/WZjOX5ZIdKXt6L5X8/ZAoX5lItuLXaIAUXhZRT7K59C5L9WxNXUYAnpnHbKFt5z338iP8WHhLbng/l2h6k4N0Knwiz80pyLMFjnUdboCBGVYiT58m8AbEk++1ZVjEjC5zySRVg/Yy1dXWcKpMT1/zkh72RBI8qZGnV9ABo8WG564Ip2HP8ABwGbwjUV2TddJxX1tAnUNDSQceTN1hC,iv:b6PyaF01XSmdK0bF/u1xsJcMhO7jHPNDs9O3Vz3MlXM=,tag:LHOPxlI5YOOldrWTUsyQhw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQME9QZDlJUGNlOTFTOXhU
            czVJYm5wVFFYZklYckh6QjZsTVRmK2VHVG13CkRPQmpMVkpPQmtIb05YVjhpdHlu
            NFA3TDlMZVZ1dk51a2Vzckxwd0RodVEKLS0tIFBjN0YvYjJTRWk1ajBoTUxXekFQ
            cThXWHlzV2FYL2hOUyt3SUtpV2ZLSW8KJP3sXV2AYzEsA/tqk/GtS7XfHqC7f4JN
            1EhqGR197NVCuo/4mogSCUi9MN4kzC2TsAIL2HOAtzlGqeUq97vEcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T22:34:08Z"
    mac: ENC[AES256_GCM,data:S9CXWfT1PthBjJ8c7T08tOqwjS5x+3KgfBe1ZqjMlRu1DyiJ75kuiPh4thKnolAc+ffwaXZPnPujI5BobEnUXwjGNlw4VilVyegeqhT9li/IfIiezccuWpr6uciWB+1CCuNRTzYU9PXpGv69cRZP9YJA6K1aaD0A6ZqrBffZ1bc=,iv:pkpmhWonY1SFvHhZVSg29U3V1ZJU7Et38YOYtDzn/y8=,tag:+Ox5ZDHeGxH3BFauPnWshA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
