apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:z4IHtxIos32GIdQuCEe7P7ZReHaMfifE/u3yWbxUDJvzAZorVHhznb2q3VgkPZcQ7lZ7U2asMeHhCGLi1yplI9GtKud7/g38h3fCBzB93nwbRwWqJEhesfnnrW6ZirZ7zvxSVVo1yfka56O7P+TEVYasEqDTpsusOpcImEx90Wg/AbHI0o1AMJNF+lFImDR/fe4Nmqu9uvQ8rb6tNtXIAwrNSaImheWOBLDy8Yo6FFShiGoEY2dpFFMYgej00hu0jFgXzepXplapnI4zfOfW12+/ZcZyV6ZmM+Bzv6h6Q00/mMsvF6Vbs4AgXubiy1GTBYGiD7Nbr0/HDyxZ/6SUvoyXax9u/v54YLzjHKaO0ykkCkw+dv6TiJfXzR6LTAdd,iv:BnL0O4lSQnoUSZzo5oHJkdE2LeHkYq6pFX+Wcw0ZoaM=,tag:Q8hFEseG/7OGCqT2QmY6NQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:VH4k5SX25IkdUa666QN/g6XMgayC+PxXF7izJ1vLmG1PWcgQIqSAlBNqvCsiBTghhoAqkuMqXgTQwiB74eOQKfd4uodIsJPOxXfEb8huRazGamy5as3gL6Yse66rUtp/B11HKNdIJHQxWLMMVaRbk0qhBdLrq0JxmXoMTF8ZuyVf223xNDuLXBIA9U8JwspTaM5lYiiA6ZhK1X8HE7AEQ0pDDqlXw9YKglqVEZZJxPBuWJTRNtnA9oVN6r3ktohhtgKJqzHJNfLTohGqWA==,iv:wkx56JE6++a7qKc52cxdQdBc+/ZLMtSUfe1XvyKnUrk=,tag:uxj5NUvs8NqdR3wyACrthQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:3/JL8zriLWtRHbbDS/cM5HYCIAHDbO9QgBQ6A6V7Noxc2Owi+Ntz8LfJJeCfLLa6a96z2fKMkkDX6JbjTBTRG2jONaOiEHnqF/ujVN2TIdLWx6r1SotRuuDXxGkmZ8kU09/LeHbAqxuDaWFOMf5eCmeIjcRqPRg257a6Pd19udp2d12FtzEg5CQD/2d1/z8WEsd0stAOiO28ZmecgUFGRwj/RY60MWxvm+rD,iv:Rt85MaMIr221XPSaNyNBU5xIZKaBQDMM0kznEcOc0k0=,tag:wVM0ZIQ/hyeunAtLIZsPdA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Mm5TcTVGdTRXR281WllW
            VlhEeFZDeEx1cWpZSm9uR2N2QlptWUNGMmpBCnpRZ1F5M29LSXZOandJenNlektX
            QXhsM0pRclF0Qi9kK01HcmxSNC9tMzQKLS0tIFJyL2VwdUNFVG95NThFYnpMcWZI
            VUtmU2FhemlxSlpBQlRUbSs0OGl6QkkKJntl9VtQ2uHaZ2Xl92AI1Huzcx8HFs96
            lndWPeYLVJh/2+cl9gIgxXWIe0Fux3BNVEOanmz8qi6citsvZkuh1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:25:18Z"
    mac: ENC[AES256_GCM,data:DI+iX6OQmajctwHSr4fgcP07jqfmB2TnVSDFPQG8wpsUuhphuycQeDHQRa+B25ZdTU+TJ36HFK1arYb4edLBZjICDZ+W6RhwiLPL/4+hWgHGpHmLjP18wJ/XO3l8JSsRjc0HQWX+PgL3579Gj/52milG2C0dEwfQa5zYqozQX7Y=,iv:9mnsWITL0OQtqhpBEpx1Pt7iUzlPuLEx8qXIRAl7Lms=,tag:dN45fcor4E+azXVRaE2iNQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
