apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8r4WVNYVB82htE2CvDnI28RgoOkB2oDkI6bMScS0SGTLXjQGG7vHcOKHJ7j8PCW/lX68yud+COg4WcgVg6FmhWIrAbdaD/0OzinUItNP7+TGPOLMckXdL90Oxkg/s510wVsHBQfxhTDDjYajQRGt8bT9Ur0Ry7D1wRfX1EJurx17VsvSIgSxvgboixU5Z7+hFU1YrRlFEbQkcr68h1eXsSONnSgTHpL05gGvBxjYzXrD5Z4e0Xu8LzUJKdbPBHeRokV3y9nJHaRyoy5xqXolIe1LkIc4+sWbYcfDsrVgmyZs9iezW7+N7zY956yXS/JHoQ1i2mi5uFJJrmMLw1/2aPeRW0KMGZmYkaLfYq/XGHMBVYv2gD9ZpqBz3jLRd6Qq,iv:92PxZ7y7Kq6BHvaobcuPKxkoOOvLc9RA1L07R37ijZQ=,tag:cq+hsDNy7DuxIQ1ScucR1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:r1VvKKpq1TGhHsDnrxBJXcWWkezZ7+QNmNOIysPoFfxavGY1fW1E690xoKARCR8sn/9LKGocOgrJlwMjnuCx2vI0sBIOfu8YL7TfaEfG+8IG5uFIQ1LKYlaexBqZzgn7Vmx7SvGbdI9ol2Nr9D1FrsTKZbTeWUzCm24ic3B3uAl00ByCg8jPqmBYnHnmoyHd2QAtCoRxTW2fhdbsZmgHxgO7nUjfABKRha0I/K4oSbNqP2a7gNiDAqmNkNadXaD8dHHhX2EzXnwfBLb7Yg==,iv:kM0JardJtGPaX4ET19AQikF7BHiaIPQQXT+yXJEp/v8=,tag:xOFBkOI0Z9xT2TADGDRtrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:0uzQHggNh89lk/xjvM/iOmqy4aB8fFx34kfnVN12tf207gBzO/Xd0cDicFasebxj4T8WP2hHRXa14r6PvontYn+dn3zXTp0d2N5xUORwedKj2LPy4XwPCOOGImGWNI9KdjhCqKzC0lzi2ksXgIGWVm0v/HM+1CTyxshN9qVSHWUAZrxL3TU9Tpj5ykZRyih0uMTvxF5IdF/HoxfIFxvTQf4eNHvxLm/xVVj9,iv:+BzU1CG/dNo8WErXDK3DJ75EFdEkbtKKCQ5KAYFZJ6s=,tag:ePBf00NDEcpqDR4ek4rQ3g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N2Z0Nm5LM0s0RCt2Zjh4
            eDRlY0kxQnZQRXZSOFhhamxseFlkQ25rVzFVCkNEZXVFQTY3THZ4SElTVDR0cDZV
            d0ZSbS9JYzFhZWloVGtLeUlkSldaY1kKLS0tIGZybGNYOVlERWNwWFdrUDlIYlBr
            dDRPY0xBUXBlMVJ3M0wyL3FtejVsOFUKAD29J1T0s5mjTxgAFsp5WygYazMJ+QBh
            M9ELjAK3BpmfG7honzbesdMVwnD571CY0kRt313hd3fwpoa0898GKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T12:40:40Z"
    mac: ENC[AES256_GCM,data:Q6kX/eQdjIQjH/Za+bG+IKBuTuj8SB8P6z/gIzZ7EGR1ZVDBmDOht/Tk+p5X9VIH6DmnKLKecQt/LjzpG5/AJ08mDLCo9YtPPFvSTCqtOG14Ps5qHkEywGZxCcuUUcSy5Kkc6dmJHZ6mKAIDjPn7Lyu19SlUqEvxBNwa2Ju6FmY=,iv:3i3o186/SC+mXBtbGr28C6fYo2jz9EoEQyriC0JJRVg=,tag:43K/th1aByJFN22yKMF13Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
