apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AeELtQVDhbr3/b0fsmnOqundj+3gq4eUyr8syFCO85SZuNyzp8zb4TVSoDEnhacu2tIaoSLQOxhI6/HqRU8eTFJdCyo1MwVIl3FkdxQIyn0yz6R89o4zDwqDbV4g7SK4tAurMnk0HDxYENV6cmOORuuRXsyS8qh+9CKlIYE0rIkKtZi94imwrz4XNuW8gJcsW+Q03itp8ITSzkXOeaEG9Qz1Kv7fIQuKM1NiYOjdtqXlA55ltv64pB62BnyFr1z9ltRqfg1P7ecTM2ITHij13wyH6Gq5ZNo5z0fBxJ7VblA4P3+UJWgEbjeiKTCRHLUBw9lT2UsHKDz34VVRrLRvz9Tnoc3gdCbbP095RjfCVg3ciRmlBct86FPu2xDLEoMu,iv:gWtEQLVmVemeVmaFTsZK1Jcv389KPai5J0E/pZ7VAVw=,tag:Ue1jwjN6pv1oojOBpHAAmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:XYNHX/Rz+coPm46YleWQFU4jcfwYnYgBrpp/V3spDH3biVG7TLo83pyTXX5NzPCCfZgDKHwrMrrM+BSdVHP4NLeWBpZxFm7OLn18UGdpQftsP/+RJ86862Q+1HIeW9k2Bda0vcZxCGqlAwtx7NCkZxXrAsuzAwte7h4TLCIBTtsN8uIGtASebAGqAAAslH7n/4kQcYgiMoAsTauRcyck2Lm2mlkQ7yFGBN1jB1pQ+PEtrxwa47nhiS2zzIXktRTXT3IP6QShKcSlR+JzoA==,iv:KzNPyY6klRzS6X57ADNNHz6LMMpus7PnwDq53NVpHMs=,tag:S2+vL4QJReYkFBfDIIx3mA==,type:str]
    known_hosts: ENC[AES256_GCM,data:DIhqk0Rf5T0Meriyq+Kju8nAlB07jYQEmSuQZO4yZCAJC7tX3KqlYeI8D9bR2oDNpqdFzeMY5a2D4JCZr1uU6H+AyEQpRMjYLlYeZDe52k21RfomWXgOSuLs4p29iIr/yWRc57UZHTT9S8wg5+CQMC52m7ZGLY6+sbJ/RwMnJ7x2dcOPkGA5ipM6OH1rj3nr49WyrjzzHqa/hUvWWtXXbuqyhlYdewkQF0/9,iv:l/Yo9+OSMWNSPwRhc3SjObtx9F7GBnQJhOXBnJsl3vE=,tag:+mBSdjpo8kdvDR+/SOmIXQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bXk0ZVFieS9MTHpLcUty
            V0pPUGJpWVpDNm1hOWszSEh3dnNEM1BCYWp3CkI1eGJVSFl5eFN6bHg0TkptNFVo
            RXd2Rk1oSjNPZzNUYnV3REVRTis3WE0KLS0tIGsybWZMWks5TGhBR20zZDA1UnhH
            cW9wbkJWZ3RubjlOKzhiTDJlYXlOVjgKdkg87K4A5IHluCMHAFhxCBHUwfavkTa7
            wQFTUs0u7ehmu1Spoi//lDjv/qmFKWgJMxQjJTeBfSGxPQJV70ZeiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:51:02Z"
    mac: ENC[AES256_GCM,data:e3e3KUkq75f6AVzr2yJOMV6PaxLwSL4sOgv8VPikaiL4NN+0xh6gmyIvb77sUqjcGdlESJMbfHVPg4pzcTmJcigXul20zcl5WYKCTnpUZe7ybWgWa36RLIU86/tjYPLzx9v3Y0h5i3ObGDoA07R82bxPQXo90v8hQopDLvT6Wa8=,iv:VPfH0BTHfu9k2CPuPy2601LFBoTv9J10xG0UmFc8860=,tag:YzNf8aj7CjUQnn/cXvKjnQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
