apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kFD+/6HqskY7o1mbaP0Yw3d7vuObgYSyL63VJoWtQiYrRB5+vaJRYAMW8mxULkZ5F8DoXNCWNWYsugVAFOT+mOGM11CTZ12mv/i5RJxltb/3ykpuNnr5J5fT3ueE/S5nJZeS7JykC6MnYUoaXiUYP5chAS4PBUswQZr1rq6avB8UXPHUOcJSYPVGs72oUMRWtkYhQfEqF64W+OnvamWWkvXMq9dpZnFIthiQSHSVNSxWaktUTTgvtEA/cWhJmAEWsLEklOe+mhskh+y4AW/N9XVJR8MtpmDXbLzlmJQOLYjkwlludDsVJFX1eKIabIE0Ygfjoo0k/INMPJSSgOddsl8C+vwnkOb0ZtoDRFjjgu17jBpO58tVfERFgftykSn7,iv:hXJ56NR0PI3VqY+CoArD+P1EjyI1SCWH3CBrY2J4T7M=,tag:Vpepf0jc1Ibh9H1YRFDhYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:KBuLUtEl19sG06mVJfU61ZZALv57YcBmnyMUpwenRNP+A/pb22Sa9ueTxa44+tw3JXz6BE1bndW+hEsAbQsWIEsrHCEm/f0cn03tZxT7hIhAOjzGBc/wfTaxh9ssXvePw1YC974jmz5f21ZiUMY9fIkYYPoUbupC/aCC9cOUB6cLmWXMiW1c6Q17+o7FF6p0maGYCrOgcvqJvF5jDA56acxPT+d5rJDr4boMBP/JgfzG+bnKKwJXDR0j+8XwolP+1ZxZ4R0oTT30DKIdYA==,iv:RzSNuLQrH9pqeHhRjcbDgWihn5VWkM2q9QBzNs/FA9U=,tag:2JlS0S1v4719SdXc0lM7EQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:B/4V6r/ebtR8cCx2tO4x3UWQGLeTFIKrugu3B6u4Mzk/0qA1IjzemGqtT5cAZna8CgAZBXN0UO6XtgFjWXyqqvOC1YQhoLJtQ+Np/v1+J38lwzk43yPiNpDqEBngAezs2kLIErYX5OReqWtiEOpQkRZZNf8nZa1ajrgSBEjuLiU5X4ipIJYh8UV6IEMf4AXEyFUhi8ZQJsX4XKXT2r7Puw6QQlIbgvh3/gm1,iv:/UbFyrnA58PuLnf0lyBWQDSp9PNjrrC9LrRrUYQZXpY=,tag:/zxGrD0M+e1nTL57tFGN3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdkRKQVVkampOM1FRZ0xv
            cEtpalZFZ0ZObks3K3Flc3AzbllPY2daWGxJCld0Yy9kOTNuejZpU2JCNnJGTHpE
            a0RCZ0NpL0RzbllndjBMdlZab1U3QVUKLS0tIC8wRnlpL2I1Y3Q1NnAyRld1ekts
            VU5MemhpSGxDVmZXWFRsajVOL2tYMU0KVzwzt1Mny+ue1X6a15IJ2IUh+AFZJ9PQ
            4dZ3wOHXRg5gd7k4CMwAUIWrByE2eo4P5sBZbN7U/5ju5mNM2hFmXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T17:29:06Z"
    mac: ENC[AES256_GCM,data:6sR9m63QtxMz6U7d750MoCIHQgIIsLdvgAmAEyVO1zl/wTfw2tAsCHMvGXdqjO50NxYyYjjA8XtvcQYqJ7OVTiN3WXYhwzpBCHqxC8VpDlDsr8D8cWcmZ8xsaaa/yEKq7xfLPfeJfjt0K1XfF5FjD3bT7BlgWRlQvf9Cnzf5Jxc=,iv:2ZINYNhA6bdGNd454mN4UUs2aPYob7iwHtbWSbOEUrA=,tag:ZwunGaoC6ymots38/H+lCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
