apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+jZIObdi7AlvOP1pEIMxU7xZCaPUm6ZLHLwBdHPGwjfUOHiQMPfQ5Rgl+uDspShazdJQqU1sQtd8erWbOPNRBFfRo7wFn/c8dsepTCIOdhqIK5QKL3FJEL/cU2RaaQO6JVO6NsHBoXaVuIsMlGwccJOh7YD5MtH+4r1BnpmKsscUGQrT64lcGaxmXyyYJ+oDpw8HqQ1f56Itwk8/Pezknl00sAlaaelAj3JiZIweYiNGJztQS+TgIq9yaUSfrs+J4vKiWVrQX+n6pPLshaXCb4nGvr15tBwA8TcOdjC+LdlTZYefevizKeKHkeokLWGvgfUdIZn4su/BTsx8gcfe/uepRdhw6CSDxipBKJx1HscgVC3qyB5hjR5OSk0DCfMI,iv:gAb5j2yX+T9lnP7HxSueL/Kqk7DA+l6YyCyO3JFdmsM=,tag:3zHH+TQoQU3VuritPrIFgw==,type:str]
    identity.pub: ENC[AES256_GCM,data:xyLmfLzG7ScV0EiUC0Kn1A/1thFVAueQ9zjG8NvD/i5yS9ezDk6tpxlIr2honnE75slJlbYOSygrwU7EJ8ce/+sAFo04Vg4Xk5vYA/Q1M11wIrhds6OdrcpKxnikAyC1HHt3Eu7IuROYOrYLAlu/epPJjffuO5o6RjYRNIyxA0qCuBwi2y8EAdYmXi01nb9MP4Qd32m5i5n8+gvwIsptHm1ktODMRe0JcCFa/wxuLFpMxxy2r1JUR2TIJwoTgo/blNZviEW3Ms3nJWNd2A==,iv:M+0CfgylX5Unm0rNu5qJuxmFJUuq65w63oeITi6hm2I=,tag:4e83MUhrJ9n6fz4mpS7Sjg==,type:str]
    known_hosts: ENC[AES256_GCM,data:5/twU+c7jvuvdX7Ycf8b/rjNeLzzcCwkqrokntQN239criEAhW9/TuP1zcWNq0f6KOtK83IR5U996Q49g8w0uaRT41/+L9v2JCGqD6zVTAB8+zo4w/RZUsy2dnmQHCgR3u1bCAIpQMw6AVt9PwvQ1BAyPxwSiJA0cA+jtR73X9B3pzKyuy7E1a62V2Vz4VyXnAHn+6MCVOJPyV/DGSrVYQPKW/CV2WHwtncU,iv:UZjE5gZLxuiRj5y2DZZ0zT+m+Ae547htRlrCN8yP2mk=,tag:Nzu7I4tz8l0d1j3nTbOmag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaU1UUEtJNmdTY0VEWW9x
            OFYzT3ZpR2VWeWpqNDRiRHRFTklvODZUZjFzClZLMCt1VytJdmdiWXhxMklGQStW
            NHZaZlpTd1dESlVENytQWEUzWnhaTTQKLS0tIHpVRWZ2K3BoRGxXak9wd0FueEtk
            UmJUNnR1NzhjUFBnT0NaMzBnOGNwT2sKX0hr1Ob9NIZZfJXpwtfs4mREQompNn0T
            jIYputlB0cm0NKxWMo8Vr/ubWYzWZ1NijCqgst1fJQBAQCn0E4Z3fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T12:30:31Z"
    mac: ENC[AES256_GCM,data:q3Q2cq/sZx18nCoRIcmc5RWIHkcjmrOw4UjODBP2J/Sb4Sz9a14EPw73DzTfpOwB+cSmomehrJAR+qAcLkD8M7vT/IfSXBgVogdTgP3q3QqNdJfhYiHjH6VsKMG2HUXB18hWGcGSeBuXxMMiqpxQqLqwNEwS92NS/dzDKhVmA54=,iv:cBpEZ7sRPeW08HjND0OUeUCPMf+j3EWmH64kAxEIrZE=,tag:D11/sqa8lCNRHz7CeEmQBw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
