apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CZc0PzxJww5wY9ABOkeZQef7InJw/da0tfNS1mj9YOWcvHHvGuH3+N9uqOEyCBMT2fBdhYMBjtx2hn4KH7u9+hw4XgT987oN5z+z8JIm6o/WfrLMFXeOOv406Fbo5TrIQcRem2YxyUvvtr4+0O2AQPeeb9DMmr2+LkP4VcEWjPB49poCuMueNid9XPsHqbBjP4xy7V9sQPd+iTda4oOgkubzYljHxAO9Lj6SZJ+M1Y6dSsv+FwZC76YOwTQUHvZzxBWEEKwLVfOlMlst2MmMmiW2V8vPeBIe/3dHu8syqomXkTUZuiMTGU5C/w/AlO3HQc2uZvjUH4KdxTUx85U4HKVEmGMt2815olASRy4sh0LXI+Ek/mLROZLRfFsKmFWG,iv:OpnaIyb6//BdrGlfGToZAc8IsDJQBkNx6NTR2drHjN0=,tag:uuc6KPcD1xOPnKELpYw0ag==,type:str]
    identity.pub: ENC[AES256_GCM,data:NFEdmp+52xkYQPRKHadCfr0VsTgxaVOhBjj7MpRGj8VeDxpELX31IjQfUcZ4jo9SesRoJBK/5HN+yY1DwHhOPNfPtofVlazqK/8h7ONqo+hlvgWyEwPJ2r6qY6cZy+b8f0WgCFCN1Rm5uv1YVtlLeteVl/ysxIwQLhwWmkCZzKLxv5SwKflaFbakvCbEmkQgdn1TIyDEc/Fe7EOvkoIcqMs8Ea+1X/Tnknfs53K9YVLbKWLzstzLTED6gZ3r3FHqX7SgKbQGSmYXWdPScQ==,iv:QevyNrzP++xBbVLbYy6jv7DezT5KpFPWVB0ca4OUWPE=,tag:8g4denGOZYLhgqEuzRMpkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:DIYBU6eAwIZfVV4gpwlyBNir0+FTiQUqlnklnLkbJrCvypuqKWso3yM/854c6KlH1/e800OT5moJrHYsAlKNR0gZGCcQ2aCtvqJkdmm0WEE4e9uAr+VyhsI/Ccu/9vR4MxAIarmg2BWAEPa1gfoBq+BveIUNof1lREJSx0FlMO1EoegX4eb4RCvS/TRM3MDbx2q2CfFkajEl92Kb3p/dW3AUQZtUXFx3u6wm,iv:MtRf9HfYyP/Z2FieQdYWsNifuX9fb37r2lHApqMQT/w=,tag:RUNTIJu5afxDUjREu53qYQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSDVQYVJIM29zbU1ZVGNV
            bEpvSjFVeEhhZFNmSWNZcG8rMlJiOVVZN0VBCmJja1lCTTZMTHhnV2dTdVdzSlVQ
            aXYvcmZiVlBCODNCVmdDNkZKdWNRdlkKLS0tIFJZUis0MkMxUitLK0hsR005TEVj
            VWJZelNRdzl5dzExVS80YlJIVUp2UkkK3kEFBEe+Mh4CGSktaTlG7ykLMXJECwdf
            YBlyUazXiVObZCw03imlXBGvRXI785aKQF4bSTohQwG47EJrTZ83VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T13:50:51Z"
    mac: ENC[AES256_GCM,data:aaZfT5jbGkrJ+y7zpWqvx2lcq8VoTBI6Q790B7vJrTbDonXlzaMeFVyJ3OZ6JgQAd9Hpgu0LV9qXOGh/lzVoP1++IG7teQrcSSZodmvzMUgBQRGeCQFNgMGXjUJutjfxXwhUWz62uWRSPxPLNAfqMTDbW21Yh2E4dHn1PeH3L7Q=,iv:f4rI+vBHkAq9PbhLNpKbu4rsmb2VdaR9MWYUQPvAHZg=,tag:0Iuo9SsMfHCUhgtb5Hablg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
