apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:g8kk4Fq2XumXSP51twNx/S7Q50IM5R9/OwfroH1E1V+rNNEH9PcXXFqF9zVxpmYY7rIw9BOJToOyIRz2wfOMHmYRXm+sMMplUCsoOCl/vPDz7frGF2Gdwi/x1ysXf1OgjPLPRYscA6EX+0lgoVxLnHOoTNn/8vvj/UJFKdCznjBOvR8eEgdKg8gmh7Ab5Bhf8b4vdnNbLUi3jgIr/p5jKLvlad8eD48vbThgbzE2+R0VWNKRe5iGep4gT9McOISMUcwOa9V71+IwXMXIwkGUW8xEVJYTDSlMT8MjcmFYSgD/tjfjps5tA14BtXqbIcChIkVU9BcrxA2SFw4h/AssVnBe625H8etvQknwaf/V3VvheHYcEFvBzgQm9cxqfosh,iv:7il306WevfY4MuI5yyUd1IW9epPbflsaEqSisdcGVOU=,tag:OcDT8cm7KJaFvUs6Ddepug==,type:str]
    identity.pub: ENC[AES256_GCM,data:moqCWbh+u1vThbKxTWBHrwUeG6rUXPcYU1lCK2CsYFQ5U8EaVp1AvsvCI6Zhr3ri1yMbS/WXXlXJzcJzIHl9GJY1Q2ANEfn+xPVUvX43y/X7FnmwWsm+yCCV6aNC3v6vE5+osXGcOOFvw5PGCM73dE//5yG/rG11GTlnx2qWAm8c0zQ8ZebUxeuTDtALok44QRWVIyB4Ywms84p4xBaGbLQTclEvSNCeW3OeeDdUCEjLOr2iAzmySJkThXCXW5MAK+BQnAjtdXuzm4iLZA==,iv:k2eMYUwug2g8Y30+IXN5nCDfl+3OO6TwohQn8K1IflE=,tag:lRmG2+WmLaAAX3GGfxOa4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:OlYPfVg0Dps8XRL2JUrfDNirG41d80t9nNakAYGi+wc1bTgxW3lJ57qmb69mm1gay8+kbrFk7QY5EL9UCxPC5GQMwKJ6IoDDps4qQisa4FP1y3yoUU6mMDBxl+77PRNXOckfsiSpwkWIwqpHBygLRsXwUBVPJVMMQrmAahb4CWclhBLzOqM8AjMUOAOVmH2U4h4pY7q90NqMUaBB0Qihh3FWCkLvA9WMCDps,iv:ykITUYnBDcrGHrASUpOJTyi9j6TrZTA1Rmkqwy8/v8E=,tag:fBn9RHh0UcV5EMfDTbFuDA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Wk1FYUJTMWxTakUvSUtM
            dDVZVHlXM1R1T2xxZUlrcmszbGVkZ0FqbUF3CkhNRDhhODhudTBZOTg4SzRpQ3Rl
            NEU0eEtSeW9KMEh1QUQwNDhpWG96ZXMKLS0tIHhGcXZtL3R5SyttWUFQUXdrMzdE
            ZTZTWVRCWWo2Mlh0UmcyQWtZU0EzODAKRsa8lrulzz78+4oy4Y3oGtjEqiJgkFBb
            ONhlWYj/kpTCtqHhmORUy1vuL7CGiIKpaJe9wZJYgLppKyUFh3KuRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T23:27:18Z"
    mac: ENC[AES256_GCM,data:PcbHmdxIM32RvCr4lP9QNfuPnye7DyrVrU0YRm4dM1kEPZyWWxyQ47CYJosoHw+wH9cJv5uvHTQC9e+YFsjux5ZKpKKfYgbdHV5EG3ctgx0kj39OVYZUHng5CXboPzRuGhZRtATKyMh6mzsrSc4Ej4Ec1WykCHa0fBpcVZMPPs8=,iv:sbjbsNO1PR/ON75bl3ZCNm+QGjeuLp49nuMu1pF5CYI=,tag:NBd1PbvBeGHL7smGm7H3dA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
