apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KSZ1eHKefwjKbjLfyxiDyvDLejfhzQtO5VvLXNFSNQT2mAarLIGdecRbHb3k//isBIpv+Cbk7Pl2mfFyCzHLA8GuS6322jdzg0E+4loMrg3UnYe8EN5zib3p34TpIadykwGDsM3VYQE3REv9m/cBbKsMflTG6SvZBKW0O1LyCulk+L9HnJXGPj7znqDlOHfU4W0IxA8CG6A0dbPsgGVdGjbpxi4gCefXnGofCi3IS4CPh/m+Do6Cla/sL/cSouknA0Fs+yGXYOB9Y7KIdTLltF7bu4JegQX3QGcV65lsFr23yvtEh+sXcfXiNGJ1+2hgkSHAdftcwcomgVnkUjvEsM1MwFicXe4RHaKiG/U06x/JurfRaiqELRYMT3tuH3ea,iv:t3nL1HgfRhxueZ29SlCevuXp0PwMTj5K+PJCqaH9LRA=,tag:qu+EDFbqy5FMxgwb3pRjgQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:m+Ggmzn2Pa+0Vz3pfFt1Z5btjKQ3zXXkCkyfNXzlr84X5k3UdaA4oBRZb/6ae2MjvML6p1DOcUl/sZ2TbpVO9yIjpNFGmCRN9GmceWhvgNjMPF1LSQQSzryFMMQGTu6cWonCOQ53ymbcjCr/xOkSJIvRYDopgEDbEaXBCOkl6lg912inhpuJCKLiaaG4qd4XaI2vS3v5RdvCtbZXk//3vri32jptH8YqqyqaxiHdz7aOrlzrdIbiBtGb6AsBLx9QimHmU2ZLHJUY79G+2w==,iv:73QxBBfz5cDQlwj13Zfq6cxxgffk20NTYgDuYD4LaA8=,tag:C6nPgJdXy5so55BBSn6oOQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:QsFPj5iB4ZfU4YyP9iJnd4CPBeIu8YZ/ZJzmd37WUPmElJMU8tYazS8egyNi3bJOWwHGtJZ1LEtxVZpqHj8qNjbN/VoJXcYEsMSjFexbCBTKe7G7aax5RzpvrN0W/JppwNoJPfb1k+DN+0W+E4TGTvu8pJ7lLqUn3jen946qNkJhWeEWO38iP9k1ltJSdjvUe02cghdbvbxG55eaSzKyZCY5Q3LGppdxyHcR,iv:q93h7RO2VoAcQ2rLDloP2bdff6Kub7YWRTPa5qxCJxg=,tag:gx4snXBKfnlItbIQwU7LuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZG1lRUhyeE5jaHFQRFZa
            c2h0d0tlS0dtT1IxRmlTZnJ4YTJEMlFGYzJFCkVaTnNreTllWHBuYkJCNThqT2x5
            NXZrMVBmOTdZdDcyVHJTL3p6S3pteEkKLS0tIDdKVWkyUHA1bk1RNE45VmM4UUpZ
            R3oyc0p3OWhWYkphbVhvUFVaT3hpSjAKEMoBGs3PQ5yl3wT4xRtuDFSvh+A/9pt3
            e+2dKmV2hXWHk5LIF6cEI7LxyQWn3gjbFHHxV3MOqHNT/S4uNMMZbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T19:47:20Z"
    mac: ENC[AES256_GCM,data:0DxERj8hI1Tw8sGIvhk1Yk7vPyK/Jm1XNMIHXgGNgtbCEGyfS1g5TzdOvOsWymfvMP5JKrXE7UN3q4La4PvymH2gX0QdVqmBaC/MQLgsguq3alQsC0kyAmN01zIVswWHnACLpEjg/E0RHDldPkttkp/pFMe9Ob1ye0Cr74NYegY=,iv:YtbPnwzGxOW5lZfkEwcEDnoLUS4fZOOnwGlZ9FXscx0=,tag:QZkTcFqRYJfoQguvHHTlMg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
