apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YLyCOmOLVCqP+2sPuR/TE6HDuA3zmIlzfrvdoHBIKWMTw3AHwDtBdjKEhjm5dFfTS/hJfmRjn9PC8z8+l0Ktv3NeKQx37hHeSyyfiHwTU9t998iz3FEQcr0jTwnsdxBICAGLj+A5vS9SbptA/2Qx1GaZ6GYcReY2Rqm7wOg+MrYj7PW35amZMYSMv3Zzpm2nBeMpjIwLlD/X0tOSUqPCOa/q5ubKPxupkHBHfU2a37A01JtYsuRKGmilnxWGmgvSHDPgmgwMLhLSTZvwmHgK6LLXTccA1aNKF5i6MiXVDcDavoMWlpxKB67lHw0HTe03Y7r7h3kB4s4+ONx3ksfZIR+sqvGLufywU82rv8BtsHipfpZlV16NSELsTkzV7e/j,iv:sgYWcwuVOfoatKcNmEE68i/w1s3BWXePot4H3p/PmKw=,tag:r601xGNFy917FzScUsGx+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:wHAvj6+Pi8sERedvebJ278nvLVsgo1afAqESPr8WGEMknJJW8lP90T4JiNiPWgvy/rEtNos1Bo9wkVrqAcI8ObsWi+FBvehEPwDDv3slw7EifgKFkqdhedQosdurKC6sL8INW6cQh0MFvxG2/cbdhB8nc5gF49iuCzX+4H6/X+54WJedEjU7PB2LvWgcoi2ImgTPWL5XXP1P+QX9qfIbz1bkCWAf9CQmdL5WJsbC6Gr5p9/YxQo53lLU06QYqIUX2ekl59j3bu88XdD4LA==,iv:rR6EK9zcYZMlVemcv30sbMWtMV+qSF6SMOuWDTqlwak=,tag:o9oPIpOcfPHWfwo0OTOrRQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:REVxzD+wgPaDYC8BIaPm0zlzKuLyHdQ60EKCnaVmDMha/+7yZDcZ/CTuz0cRlc9Mjq9QbAXFMCxPsc42EAxf1dRZAsl7ukQy7v+b2r5OxSpIGj8BKBo+SKsTCCDL0IWcOCPumhWVAHiuq7DTvvMJy/9qLw3Qi9fpH8a2iHHg23MoWy2pIdvXsakK+0fZ5Rr9pnMFKDGqQG7RwDwOTj6YJKmKmfnAkre8vva+,iv:kQdrrfNaoLZzob5O1qW45p4NjbsJxvH9BgkBVxstJfY=,tag:2qJmksrStuQ1e/MXBEqHDA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Rm1qb3J1ZkIyWExFcE85
            cWFJdXRESmx6RU9XdWdsWTVDTEk0VVZSY0ZvCkJzbFZiWmJqd1pTM2l4SXdMZ0gw
            MW5Ma2FRbGJFd09IUTFBaXE0RzZ2bFkKLS0tIDF2OVNmTmZzUmw4dHdZTTc2RHNK
            MlEyZHlkWnMzRW9udnM2TmJtMlN3TmcKqtyGUrlD/YPGNCYia+JdUQT8flIH1A7Z
            dS4/8nfWO+f8Z4xduFYAFKyFjioDLq8jqrpnnL+6WdRw00RjSlrHEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:40:37Z"
    mac: ENC[AES256_GCM,data:a2HC2R5mRnEDO6X/ixTQyCLeE3MQBxIOqgSyj1vmVO4ZmABb80CnevYtYVPcR09bobRsACvY/KrtbQ6oeiqvObJPKHAhicIGItg5CnRgjLTxvd1N0qH3+IGzVlTRSlP6pOeyW4IriqChpDb0+IgM/jCQMkZx7imNMJlHmSoNsMo=,iv:5wUDbsxm2R9b2PJEijTB7f7VVFjL87tA7JLS+KkU+kM=,tag:Q5XKQj+ze/4ytw55l3IV+Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
