apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mUK53lllxfM2ExVPBEV3WCIxTsgiMQNV1BSu4j7BS6Dgfq4MOqznjwB0zYauAPY8IEiuVCukSPLMnGve69uArwfkNFPg0TLZYYc4jdDb/z/GXuOD3Mr/6pTJ6WKBUFM57Z0/FkDQ81ocYl2bNvofg1KYAoog5y9qmDt5UJ/g9jKvBUz1FF5OjbujJ3PN2smvsRgojNy5ql6fXq/8yMhBp1eutM4huNm/xkNrB2h+/kKRCNK70Kb24fReUpOAZJ3n9PtvOXswcpOemlKlEeYsNM+MFVdOa8SRBuFn9K7ORPvwBm5LDo8oUi82XSSNEtTWk9FP5Z52zpc/e2tuFMHeXNnmOWJMSC4YogGAwAGiMEzjjJ/RUd1mawcbxHvB6Mo5,iv:lIMFs6cig8TPzE2uWQ6RtjvffycFgVp8TFgqwllzees=,tag:e9zvClOxdmKIPpH9euBFww==,type:str]
    identity.pub: ENC[AES256_GCM,data:BYCKUmTxE4HnReSUgwqhzdo7fq5ddxIFEasSyWdLOToWtuVR0JLcLZ2iVd9UHP+wCEBZ3aoxjKZeUVvGqZ1zAeWOHEfV9CFHi9AKbXTSHfPLx+GZ/A3Vy2qJKRIqzoVJdzHP+bJ8rbsjBNzXl2QJtQ567zb+gs655wN7VS4CU8UW033sjzefHlz0MLpofZS6BuS3ylGcZRTUuex+RV7s2T/+iSm3hTaOoDyNK92ev3Djs8jgpQ5pp5sNQ5TdeOWJMhr+PJMGS97ppXsTNg==,iv:0XUAMhN2QxG+8YYo4zRt1Z8pcgErgjtawjhkYwYDM6g=,tag:hwk0IVBf03Li1gIyH897zg==,type:str]
    known_hosts: ENC[AES256_GCM,data:pb8ROonJXmHgsa5MAZgYQMcHXn1+reUR/kRiMHqL9YCpc/HxYEk99l7/HWw7APwyKF9zMmMkZNFjwxi4We+uSsq/s+Mboz8kneH4JfvfIXjd1EXMVbu2qK837xxvVdxDvJzOIsusRy9J055sQxGEtcYPGT0HLfonfKPsEKTRoKp3jyzahmksX8dZuSFVIFllEbAX/y5Tf3Xu7yysU3D6NtraXYG/BaHwbwsp,iv:M1p5ZpjbA0xWQNhAbwHPOfcT1BzRtNf3YPPAFTANT5I=,tag:ZYLpcHmiWpBTJ6Fs2ZEE3A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VGFabTlna1NTWEZjWHE0
            UWxUcVJNaG5zbnRJOVdlbGtReWVrYjM0cUNRCklyOU92YWFlTmdPL0wwVFJqOHRY
            NG9VNitNUHBRd2JNaHk3dHJ6NkIzOHMKLS0tIFk5VWU4d0d1VUpKV0F5YkNpdGVE
            SFQvblRyV1hVcEFwME4wSHVtREFLVncKMwnFUzh84BrLc623dx8xsZhYD2IgS1t+
            riozTM1GDR7LzOrbMT/MsdE3+H90oOida1QiIJD8C+3XtKGSEZvghg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T12:28:31Z"
    mac: ENC[AES256_GCM,data:n5rshcws6HDeUqm1oBV0xzpXb93gZ2ceR31AlPxYpI6GPziBT9muIJW6dygydUe49hKWkM3Ou1dHHVgJTiYrEaIMX/jdU8i/HDYLB6+axD0ftIhTqVSPPPou2eCDCKIK8dFJEvHYk8jhAoqruZrzJX/+3wvz2I2qGfGTgbaFQKI=,iv:pjQfBjtp6h83bYt26JwICTvs8G9ftXKIstdNswO8tV0=,tag:lbldPAJpv4RB5KKdyZetKw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
