apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bhx/l2U56P+fmIkwxkWwOndu5lb2lSMFSxxlb/QNQghYDdpKLeYkdn9MdT6MSkUU3qYmArxCwEJnpW1DKBmmiycOSQVYbZVvdB6HuSYkxF4Hjyw6naSaozgUowwCQvMhAbYG0KjUNLap2NnSxI03fhxLCCdMdu4p/hp/ZXIkfgIVD63UlYpYFd93rTdjkiTCmdUKnuhHI4BznCMGZFqXU5XGofAg0rv+cmeOBedMizxmGdASb7Eejrz7XMFb46vDucjeN3SXnKtSGOAldv6nUwZU0xLsDRvXQepsjeDFzzX0ByinKgK1/H2q+QFLjzzYb0qn4mtB0p7Yt2ZY6BpP2jSm07r3WwcZ+W2KTLk9Do+O0zRQ+b1xi7Lb2q4V3S5x,iv:PpyoAnnCTqdlDB3DZvb7WiT2Eaup5MCxND7eSpUwATQ=,tag:QvzpI0NGkYVSHTo4AozOBQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:xmzcxKNTUSDbp/h71ZJJQRU8v5tR4yqRPylZaoAITjzKDMbEWyD2ai8euSpQPKFT+rObdkFF8lA+7/HF/M+lc8Tt0Ey1lp1Y4mFT3hgPH2hVnhfP056YR41Oeen5GSFg8TxDvPSgNT2KzUJ+nYTw1L3GOGS/y68NUR9mO5vRXSPVJ75DStSA5iD3oQq9BI4XjdODD0Fh9kJWkZXUP5emm078POpE8A8aQRDHlPvGNSmVJ4EBV2HxR9FZbSY6dTx7tzMR/ndTrxLARA21lQ==,iv:5mbpQ/k6pRyd7DtYDjrsf7Ymn4k3w48FvKimkDSOsXA=,tag:81H+stIZgoenrf4Ljrmn4Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ue4g57jIYphE5/tWrBIjQF4/RGBVL0oVJ1e663IO88gJylECwl8Kq+xYHY41nKl/fMzpy6o8B8RabRV+3uDT6NSSQOVCRy3fgYV9fcal+1sW3veubxa2bQzfxZYZmHz865CWTCsjmLvMBXdGCB+eTnc3xkJAHAN1h+27iPhq1gcPsaz0mUPzDV67hmmTywh5d4P4IYN/VGqruYObWO/CdFZ2YotChcyyEjG2,iv:0B9g8U8fopfhbKDvCX9ymhEriKfBMBD2v1qbcUcKCVo=,tag:/J99QJtl6pXch/oajzJpXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMDk5N081VURPQ1duZHly
            bkJGdUNpaUxneUtic3JOOGZmejZhd2R3Vmc4Cnc0anQ0ZzA1NGpFMjRwMGRUMFJT
            dmt4NU5lUWR4SzByNnRRcW85emgzbG8KLS0tIE1rR29KK1dtUUdyUGg4Qy9oUmZ3
            aFFkY3BYbXo4ZEs2MWJxTEJJZFlWMjQKTfDSR8YUaYxqQeZhe0y1ZUthPpx1CVKV
            dFLfqcj+kPMoIE8rrW3MIAs49hr2hb2InOk86HmyngccEA9runj/yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:40:26Z"
    mac: ENC[AES256_GCM,data:FYOHCfnLjJoEbgH6/TI1BNatAa13vOcDwtBuhMnLJus8KJgROZmUr6nVgFl/Pj3Pn2jdO21U3t4MI+XRDMEr4gJjTLqeTkZMLVhJ3ZLkaSZrJuaWtZVVZMjZQUNi3uJgl/+I2EhO7HcbxvAJYOQjeMrRJsWUzZZt2RrlWWOMgZU=,iv:9eslyl9cmlSq5yQQOEhPSGJ8t6DjMt0y+H9QcbNs/2g=,tag:0H7Rq7Ki/erIG4pSpNQtYg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
