apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PaqMXExzqJ0JpFxQWLRBoCnVBKx8A5NGnRdUvtZqdaF61wpumcbKZMPsgWlds+NXkWCAey2wf9JgDPd/KvqhbRBL4ChgE/+qhKVVp9WCwvKDe+Wdpvc8aPs6MZe5LkzARg9E4238um0kRFov2aUfOTa+AgvvceN86PEVrm5NXBoSNuKnMb/aG8Iz/It9445TYtHHhxCKMFUJdP6Xmuy75HzmlaZ3L78lsgJyDGr23q/dMF3JCicIPaWHePlAxxqV8LQeqG1m17/jMgq0jStQA7DN0CjUlHv5FFu6A4DrzJL13Kt7hOjV1ITyK5q4eT8cjxBNHyNsh7eKr5O0NDQ+3TnGPJZfksGwBNcEJnsoHRkVTdxROeOUfJZFSdnBxWFJ,iv:inEV1AL/CHa3XLPDMKHO7qoOfU2peDJyS3h+E5XzOuw=,tag:CCkF0s+CXeHY9jHXEUx0MQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Pzm1qjhg9V5IJMeTa3Z43cdyY0AaY9Rc+g7X2VtP2XmdDZxLjM8zWbAVWujMgI3TiP7jH/BJv7cGDGIfPe4Pl/yyjK2Pzh3xE9nFeKsOvVs8O1cwFaedg3NO8Lc036I+ISUppFSDyxtS+2hWRUeSM5E/Vyd1cCH3CWL/xwJ2/c7ymXdVHvhMfxFEuPZha6gXSCYfRBbVT2F1F4LfuGjcNe3KDtnS07uHNZqVsA1fo0WGkf9JCLQTELiItwiizSBwKPUQ1xvRDU6syxZE7A==,iv:wfRcVf03+OAHt0SLHQAkY5JHCEtS75D/5x9L8jCJVOo=,tag:aAPx2OEkCKa4uBlGs25Rag==,type:str]
    known_hosts: ENC[AES256_GCM,data:bigV2MdjHAxMcEf2SMprLuwIBKlZJ3wuSe9xea8msXm0fnYTa0F0jYDwmVWQPFL7tzYZ/RgdQJbPzMrT6caFI13j5neMdINuel6f/NR9UxcD4XSR6eJ+eIWAcTZjIksLA2Ek8RWHE0oQgE3GZwMFzJlHTpY4cQvYoSDr5TcINETzkE3caGldi++dsO/eO0GYSm2e/5QNU+rvtynpWfBF1j5QGlF48TdY8ivj,iv:u53oGd3d2nUQwCip5wqYFcxA5GNAqsxj59c/tfvZiwU=,tag:gjTOeUm3D9XRyrEo8bPYIA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWnFSZ3ZXRmxaNStOTkcr
            cmxJN3lvdlNaU3dzTmNOcWVKeFV5L2xkbUVnCndOYXJVZjh6aEU2emlaZzB6NWZS
            Rlk4RnFkR0VzMkp5bnN5WFZEKy9sSTAKLS0tIFRIdlhwTHFTUHlSdkNSbW1iUUNS
            VjdkZmE5czJaSkpyUEpSY1FMYzk2UkkKOANDumbOiumALrtrpL96E0Qq0dN5mZjb
            E4ctGibJRz3tUOvAej/7+Ixyc0Lt9DW3GfiH5faDTRX3x9A0IE88DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T22:33:46Z"
    mac: ENC[AES256_GCM,data:C1AwSZKtDR1oMqTCWohxNzRR9qYnqpDLrXpNZgJuS2/73dODT2D4LIqLy9Nj18cgP7V5o8YB5iwYw2nZ8/RvlM62DIP8bvXGmw+7FAQtblxnbkupjUOS7FfwYrn7DvYt61h/wGQmUK33VOwfHkF29RQPMSfjniAz/ICJ3UQOYZ4=,iv:kFRwG9ile3HC3Saq21jLK6nBRsGj/7vUrQC3R22nQJ0=,tag:fmQI8l+1K2wQfHQiBu//Ug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
