apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4GdFaXQJ/MjgEn7TQ/RIx6O6lvlpARMb37P/hMPKbTKBqWi/MDoOKi3WrLSls/ZdSf9sAb1c2YfSHQFMTWGkg9mGuVtZ2iYdjTctFLYItbN3eckuIBsxwPod2g4xdQio/Pq5Va/tyuzxrRrlXGizQ3yQUeCfHo7h5ZAfOCOi4pD0r2Xy6HlirojQA2Wko7nlcp3JXOQNu2zlbkp8oOIH8mMeNQSKPvKm2eVf48quImsC4Jj7SA5dfV9hRc00ifOfRYPU1m4JB620jHAWNjdMoC/6mImVk9yZLDGKU0nwA6fmIvcQToY+0ooUQnvYBtE2nTWgyyX2Vl89JB22WOmp6CnI3K7191p0AlRKKkx3UezInKGP6tF1j6sTMdVVy8vN,iv:6IYYaQDQUUEBMm5yvHMJQ9A3ns6RIYKAv6Gt2jcWqzE=,tag:8PRm0lyR6td8dolsHrQJXw==,type:str]
    identity.pub: ENC[AES256_GCM,data:7ugFXkJO+6w8WZ5jsqxHf7BoU9DBaEYl0Pt8Wqs2e/2Z+0Quh8aVGqBvxZRLZIRyvbaRY49HOMgOFo+T0NqoQjRCUGy+ip7F9PrQqPE8DRpAfaNIepUYIkZ8tAURuP6jEzJUiblID4dcM3uTUajONK8Et2A9TgVIn/uSCG1sRRCCxdvOlpn4qBw4trWp11QWqkK5lAhs8vys5cx36/cC3KW7V5c/gLTkBEI+r/6RZBsM2NCHSLP6ThOK4yuQx9b0uGE33/edKjZUUGZBow==,iv:qwRL7Wls6rV+PyKJ35oxwpRypTUk4/Qjnx9MR4YzJg4=,tag:bhTPVUSAXxGfQVcQrTER/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:2qK7/Xk7sHseacVdXT7j0iKac9PW0itJzUOet+0+GwOO1nEtPErAeeAcLQ+PWsepM+Ffmhms83jA0FYmYymhiBfxK2bd0DS4SlBu53OXUDp/2VX76mbwLxfzovAzgV1o26zm/wlumZLFhPhHH8LCV9XL4IM/SHfzq4TPVu2vLen9B4foOyvX/C9k+dCfBZq2Mrnh4xQZK6Vy3uehn3GsugN/qdoUQnmT5bB9,iv:VScnKeg7eLByq1YoJw0DmRZV7TFGJeixsZoRRa+EdAk=,tag:Iq+pgBJyCYOyHzXfNgFBSw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aWZWMWp6bUgySy9sc1JJ
            MHJWallGSGZPcEwwelhrQVJwNVNObEszR0hnCkZZaHZ4b0lpdGtGKzBtSVIrSG5S
            T2ZpWVRZd2thMDlxallHVHFhYlNoYncKLS0tIGpVNzl0Qm82TzQ1YTVZMTRzU0Jj
            VUVOblBjUUlMMUtaRmxxcVozUitnUG8Kul2my64h0775e2Qp/U6vqT7RslD+xC9G
            Klk3tn0J6xyJSuw0MreBfv1VGQimX9vzJkS8xu+wiqvCh8rZRMRz9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:47:20Z"
    mac: ENC[AES256_GCM,data:z1VXSyERPE7/Laq4V73B935Z3yAb7+lhZUn7/0J/58KI57KyZ9o6cSYZori/NhYduvX4wn+BMOXNaNVofeCMOdLQdt8fTAle+sSCcoiqY0qbaWvOtieuHeneXpnKlgk7DBgkW7BFkqE25H4JxhPqumJRRhATOwSVaBa+fHCT984=,iv:SbQ1w0YcDa8rbvgNyxfELFhd5DvPUbjGTWV940WEs7k=,tag:UfF202S0blXxJdYo4us69g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
