apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dCXUpvk3QlePRPdvY3D/SdPL4P7kk4l5rzYCiUybCmUtXPHjQOQslv4VrS3EWbX8FEpqiYy30xR+P/EJXZDe5Ga0HxaDOUY3q2id6vo3eQXaWv+1OyRA9vaE1VP1AczeTSRu1XdOXHcjLpNuQKNdnpJJ5JGF0JHOG/P344InNIv0DSzMh24Z8Qr3CuFTf0mDz7erVQvH8/C2bgUg3X968TfC3ajeICm4mXGihTSgSZkJtaIwKERRQ8QomyfpgFwF+HGNpa07mnDq0GpWA8KBAVZ9+xodewmp5qrr6nzn3XOMSyUhW0nYmhtOshsvqv5OOEb0pokaPQiRUFQ1JfubmZ0dJ0ftn//qPw6aQBDQwhHjecMGJ683mUTT262FOBPu,iv:qIUeD/GEmuJdEPXLwQ0uGfx0TYCDGNSualjspCb/eY8=,tag:v657QdJorT0KhXL1P1tAew==,type:str]
    identity.pub: ENC[AES256_GCM,data:NSt0QWz3n6rPHmnRMzedrbUTXRoKAB3cBnAJ6AibSz3IBrD0J6B+zzSfEjVBLfmEo6x1QAg3KooBD39fvyVw7maex34n+h2ewt+QaYPIAULM3vmq7jfglAD65X+baAtbnT9JusS9A02f1vS5dDDUNVZKjzMUVPzBd+kGrVWOZCH+ud4muB9U1fPVkY1r1kXxvJ9WpHHalpK+Bcn7haaPXr12xffyw5uVyW1f1eaXuvrvHFalcPzegSoP3oI1Q8AMXxJmeN0CuUlyOMBp5Q==,iv:PO0j1Sxz3e7dXYRcaCMfoDBpI39oipaeSEkHUHeu2tA=,tag:3+f6O/bCZhzxaSDzmB2TtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:kY3E1dGFoSfGYYcwUWbYgKHFHmMqWlDuA/kvrSekCrOA16fvCo45Zgzdb+W0zd66IVSNgIMEogj2iO8h0uwa4WSXCfchvOf9gYC24YdFDaRrwlM1dGWfU1mN2lKPzSLajj0ixvExY7y12j4I+wsLZBO/SNE8gsRMN2LGwSz6vSvsark6sexc7y6/Hf4MAlQDfrI9DcVTPT8H+swhHeXTHlBU0eeKtpGwlVLr,iv:CoyyfU2diok3B2FFD9HnrGp6BxyCedrkiGZ3CFnnw9U=,tag:LrKihzrUDUmxl+kBoSGqbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OUYyMlZubWhUVDY0QTI3
            cVpHNnYySGlXYVRHT0hyTWtTNkFpVkpMS3kwCm0yUjQ5a3d5bFVpaFZmSHE5RVpC
            a3M0NGtRdjVReVhaWjhvUlB3VlhhanMKLS0tIG45bUI1MXJtSU5Sd2VIL0lreHRr
            UHJybzhuMVFSRlRVdkhZUDZOSm5zN00KbELUimR/GDz2bX/EuBNS4HDEQCIFUyoa
            usf/jMX7pIrH0lDbtF64RH37Ecaa2VEMqBSzcUaeY00LVEZ++HTLrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T12:58:58Z"
    mac: ENC[AES256_GCM,data:5VRddj/b/eFSSyhSRR4ZpKM7KY7sfoZSQomuBepBS6bHlplmRnFhj1gVmlF7X0NwwAVHcq/jH5U0Dg63RCHWTRS/IrE0fjMHuZ4jL01TO1/pu8bpGUSBgqNAxD2BIfWeMLbTgrQ88bKfAyp4HPmqoX1Lnn55I8aZ2erQ7v15ElA=,iv:KQCdW1cvat3UUj2qsBntmPkuAHQNo+Bdtif/y3NJS7c=,tag:a8j27FeOR/grxDqIfeq9tg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
