apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PdqxeEITNI9rVAnLEmHLqlrGuVD8bm6aP8v7dpDJ0Ix0RA/uQvlJ5XMffs/+dyifhVP9nt7CLVX+OHTt/jQeBupZOqg1TGfJPVa2baUFW2dbY0fb4kDzAyQjjg9Vwe3KShOvtcto5wx+ZEr2EUEvd9kZg8hhUS0AzOXkIKPTZPCKkAgiE+KcLWElHWQx2zESSd0Ex06x7d1+IathDHFka1sWH+gJ4r6dqbXtKmabfOscYsO+6fZatFNoHX7AGSOndIBq7qAkmwJ8yEi+Kp7BM9MOokmiL5E0KIVIQlIv3mMoqOJ7Z8v9H2O7xs6t+Myt2J1/tYN3uZ4u7F3u6KZRc93aREBZoh3T52Y/IHdPdrPa+ZMr/lmApcNdJi+UsECc,iv:iSHT5MiumWXAu9Ypqbi82rKI8fuWrT9vBkayCVAsyrw=,tag:WbBHhZA9g7NNM0CrmzHZjg==,type:str]
    identity.pub: ENC[AES256_GCM,data:uf4IuKbbPSvV0ZhA+8idIi6y7S1dCFmKNNZpRrkQ29rcOBBjJaX1vC1txus44gXtSu6on6/KGmy/i2xoQjNQcr8WMAtTOTDupa9imI1dhscH2xlFpKq08sCMDO3vg2XU2P0MfBSqINqMXGhB/9OK05l2YKf3FTRSzwxC6nvpc85plbmjq6y+kwmMmhhMjFnffvtHn8Ry4T6NFImRh0fBM9Qa2WcizjUedbNP7zwcQsiqlxAG6moPoxga3q8+4FovN5chl8UAEcUQ+gbVDA==,iv:YWhcdS/cKBgmNC7vgTaR8jM/Se0E+QqoPWLbpI4jAWQ=,tag:ZsA4n6MIMiLPx//M15QLpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:fdgdbpUJxhzuga2w+ex5AqR73Mdit9lTYrlNMSyjlFwU+S1e6HYSSARcQ/x+0s61CRDl1Eect8uO98ldkOWpHry4Q+hXXx2f5BhJy0SRGJJ5lwr2M0cIv3S1muh+72RRwih6fL0/zX8GXWBlOfagNWKcxYl48TMk/83SEuo++1aNsC6O/H5zeS3wwRPnaBkIEt0BqAS/Ai9iI75t+IVvtuOFmZgoUD4jMUgP,iv:B8rM6k1wQzl3AINPyNtcHY04QRFON9drouaBC8uY3Ug=,tag:bD/SB6LZ68wRxi1AUkdwUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSW1nN2hsR2wvQkt3OXo3
            WEZqaUhRQUxKRXZlOUNTaFAvNXg3a3F3T3hFCmxvMFQva213UzZlZVlxeUtxeGM3
            ODd1NDBXUEhmcFBYeFNoS3MvS25uQTAKLS0tIEpYZktvaUF1R3pDSW9zK2IxWFI4
            MW9FK0QrK0lEM2JSdWlna3dnSmROS1kKinVyjXlDgNy2SwdZm4JEnpXpmL60X8cX
            tyCHFrkjCAa38mjzW7SNBKo8q30df7Dy0cse9+qNn4c5Qe1jcvyN0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T12:19:40Z"
    mac: ENC[AES256_GCM,data:h4O+02hfKNwdzLfJRfkHSemxx2Up9yeL6QML2SefB1lU+na2z4T46qKuX2+2DJHqf+Cfpx8C1WYMW48TY8T/JP7oasvYxrnP2PytbOh11JF2CALNnH4+MOyK8nChTMFd48WJxFvS5xDa88CKeol19uLyRxXTcfFdb8FLzEIQ/eA=,iv:gu7YOW1H8mGESf/PFFcgWfdwrlZgfkH0FdNVhBuWJKc=,tag:X1rCYBGzioimChZPu0RGQw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
