apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:B6/Pc1+X0CJxwQznW7LIpTp8ePR7UodYVh5//zpEXYG/54Pj8z3ZJmeVWajt/gX2blHZsFX1kCshL6r9NGnDyL7B3bsiANiOKjZ987xmmqrkbaQBLXNr6atv6XqIJ07GBaNQIRrfT9QC4u2/TMDO8BmXuzF/tilcO7yMbQCEWLmuwG63clebo5xy5H8S6JPnJoOsE4YMCbZb+IuOG/UrN4jWnYeDIic67P3k1zsHI+HcIlmgpZjLiWt/97+11u469RPVj8UEKUNMWTauRW/Sgc81NXlGl5PGehPgrrwpLOrgJztVQCWUTRXVEIlHJkyVRukSLDcHcf0r1534cei/IpsmsMNJpTrhEDORhNBryRa2TwTvZnoyN1KHPAnuIkLD,iv:9+zg6mI5dFsk4ZyrHNQ5pbYJm88p5l9EQ4eU7tGJMZw=,tag:77rBOKyAiKj7KUJ3624KeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:fWIGqON/P/kHNvjAtxnPthI7OIjlMbc/IbgdgxRPTXhYj+APdiRavxTvphSUsKEXz4DLrcIFLnuuo6S+S6fZMHo8hJppRdOMnf057lS1JweNthLfuTK6uk2DdnYRUGPLtUULZqACjNhOwk1UF9TPWMJIyPFZaNjd99NK0L1R3YOHuQVYW6MxixbHbCMvr/zeYfTsgqNt7N6UcDmLPzzUMmxcIaQ0RQcydvTHEDNtnh7DzBTM4hyTNG16NbNSjgjuKN2kcdAOl/CRsfr5YQ==,iv:bHhknjsYwsGYIiX1q+wNT8mDG1BXtDyFbtoPirY6yY8=,tag:zVN9/WAl/vg8D4pAg+z/og==,type:str]
    known_hosts: ENC[AES256_GCM,data:pAoO7CoGH1WlziuyvGWj0+R26nvyY2awEVvgZ36XhkmqOTaCf8DehBEcUQrMzP4NRxHtPi8oN23KQsHQQIvbWdr45sI+tJrT7pLscaxGJeVpPicrMvBKd/UawWfZ6xtfnfQHiX0QwzKH1Gk4sO8sF6Bc1fCXZaOyEhPX3CtHOQzBsJXfWSFRA6/eJphlAcVxWTzT97oVZRzsVMssRyTgM8DwTbYvUrZmRoPC,iv:Opz/Mh6IOfyxQuAD5AYA6GUSh7D12Nrmr+kOYP462Io=,tag:PTgMai0VcwFXs9SNiWKcVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TTVsNUZhSzhnaE8yNzcy
            YVYva1Frb1dRa05GbmZaVDZZdHlJTkkzUHpBCmhVaWdlQ1FxbUp6cEJ6WFEvMUVB
            NGdmS2p3bnpON2UvV3BsY3R4UTZ0M2sKLS0tIG1VSEJlbks3TWZQZ2RpelgyWTJk
            Y1JQTW81ayszTE05a1c2b3FUS1dXSUUKlptbDI8jYSP1Ig7AODpR7FTpQfDpX4ht
            lG8ylEzUdMrH8IjM5IbaNDx1psLUxerUiFjuWPDsW5xfuWFsyPy3gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:04:38Z"
    mac: ENC[AES256_GCM,data:XzXZ2OY8YHev84972hXASvT8joE+qDXPHJ4qu16CPQGHJJcFZ3ha+08O21HZWTu8spa0i5qE0y4epBa8P437KFhFRpezLbx2CyIL74Tk2T3Uq6ZOjF318MBscv8GmAHCLnt08iiOzpXRUQr6oH2h4u97dLjVo9/aqm3k0dLVQ0Y=,iv:hDCMSpomEPt7FYHDQ6//FCmmZ693iorkAC/V/0idoyY=,tag:uGfZV1CGVbLE/Ga7PkPvYA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
