apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YGMxJjjyvY5eowaBxAk12j+fazNnJQfxJ0psrIPVFahKpL6OLkiSnNnKKtCJek6CdPPmtlnXmVqLND9w3qInKX6rbpB4dVJcJ2Ua5IgBwH8rcg/Nkl7zO/w/DDgKWXLAYO/gVNjDxheQPek5I3DipZlL/9e7Ph+pJWjgTdVO8Z83HndquFyhS7mlorzviO2avIb9Rrdb+i7WIVwXsAZzEx5gOjqVHk5/NaKfjASj4u8CKY+eT0uC2+y91Q2ogILIH4gM3CYVKxigcwa2d6JZSM6PuVopa6xMC5M8Ri2lNEE4vrUxDcCN+Vp/lvUEKs7YBUJFiHGSvjHJNhOZ6ZIFYsUgsT5LupwDq3DG/HUzbt8VWTagK0i67tDr4+ZK+9JP,iv:8nhCZFpOmJqXbXsbwuhqFqkbpIUSVR4Jc3dbswgoyls=,tag:7ifW2WDaC4Ia7AVrOTxqFw==,type:str]
    identity.pub: ENC[AES256_GCM,data:AuV6xirfMQY8cgn0yuW1PiRqWA2Kh/F584fafG9ECkOEZOa4CqhzchRdJfrfyGdZQNpRs8dlnUx8fyiadsVmfHmiNjCru0MXY/UKzThkilPG7eP59Ijdg1YlZOnV/ncwP4B6PeFrY9ciL998ftXpX9rP1DTEFfagU03/6lCgHIzTDQxpVGyoqpsSdhQ9S/BmUKG79pnLodMXGNmlifig+h7di6ueuCl6ev1h8X+v4+ezheczPkLlA+UQSu939rzTevwIuLzHDWtq7qprSQ==,iv:7W74n+pTLctiiSnjVfUqFi/8ZwXOm1JkMHY5j7A4TJE=,tag:kgEBvj0/C/OiOKgXd94RwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:J0UngYkcWYW2YYt6mcOGFsBg9tF60CdHA39VgvCY+1fGZK3wpvuxaWgBjCUEeYVXc35LZSkv4Q9cmtS/QcP3Z38IEzoSP0nicow5lWQnXsYm9O9Q/ZQ5ivA0ddit8P6s3JtUlULW8SUC7xgm+liNTR0CCZuu4/+joZHO68Qn0gWSa48z53N3oXMeygID5wREiWFN0ptigzM3TleGvIHWLvTcJIcKB0EI3D10,iv:pFFLILfGFoj8B+zlb08yKSlqYaZaXVEz/DKwndjLT9c=,tag:ddKnEiLTCxnpdlEUpeCN7g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VlkvdSt6RHVkODlYam9r
            OERneDBlM1l1SzR1ZjVESnJtOW9ISGkrMm5VCi82R21KQnBMOUtvbkRZVDE3ZklT
            M1dvUk84Yk1rZE1yZ1ZzT0pVNmJkRncKLS0tIDVTNDUzSGlxOHZ0TFpndHczUmR6
            cEZjYk9XWFk4UTlpYXJXSFpNaDB1QkUK2B3YRp5To8ooWQTpj4P9T3ee3ayhwryQ
            +G5+ZTVyo0vYcquCYvCa2l8lm1bmFsrpI1nZAYEsncKHd32cDl62Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:28:13Z"
    mac: ENC[AES256_GCM,data:SX3HNoCYP6K4nIoy5YDmbh2FYWf85NIlP9CyM7pHUXyuTpR9VOpYGPOX1MBJIC/9aSnyawghgXd8VExsGRVALArrTNHiEsGnR7+UoyapSfLtc8lB09scnyzoQa13kkA4GQPzpwGV+YotClNr/NdSVTbmsKIQeOp5dNxocYsccIA=,iv:orC6MtuYNtI4liXyDM6FN+7IX1P0kiKEVz7v7H4auSI=,tag:CDPwneY8KerZfVNx8BEYhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
