apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HKZRtY2mzWKuF6w5CQ1tBQWmbox+zm/ECtRQmUC/0Wggjxcheq7D9R+5fFeeLQyqXZve6r7WI/ZjjccnLFmdT7FsactnIlUeUBo59kZUPKLL+YM+k37tjOrGSrP7fjC/HBHkKnQHuNC7eV25CfP9R5vN9JrN4r0ZJDQvFfyv307kN3y4skqLPvD0ap3b0SpGaBsIBEKTpHP3uIGPdMZx/Q9uYyXUFoB3I0nWnbb5SgkraHA+3cf47ae05qgECaMFJ7B3fA2gOh41CgfXufls/jT3Ob6GzjWYAI9uhr2O5PrlR60jb9GDjbpVWQcH1e1rAJIn2YFXGtKLnZBW5imnAMd6qNjjBoVrx4141AcKJJDkkCge2ivj/T2ludAMjXm/,iv:2fsrlW95DBca1VavpMhbyelnje7NYHpGltsVBa6OWyY=,tag:v0t4shjBWFavvGN8AiAjiw==,type:str]
    identity.pub: ENC[AES256_GCM,data:1BzS8KfDc5lmz+GLpPUK/5097lbjAb5wU2tXYJyFsImJ1IHwN2c/YAqXD7z1x+YbAEK0VSBts2N02EFPmM7DF34+XwWX99UDXYQjXIm4l6z2MyYVWv29spND1dC++oeDHXnKUxMe6KLzQZVAxgrG2QNwvljEUHn5N5VH/sAGOK06My6NUGvhaU20wlj+JN/UOkxsfvHJnrKbXV8bS20D+Jr9v8L/3SnnbsTNGHjvob/oFFagJBvcvyONNb92EBhKZLYabsISJyQHePUeDQ==,iv:PM3hL9tdqd6/cn1fVgZTLOAetz8bZt0YnVgs2WDjTFI=,tag:3W0olkZEMMdyP6NN9JLOBg==,type:str]
    known_hosts: ENC[AES256_GCM,data:aT4rA3dxwCEOPDtOJgD/rJ975+JgWM1vTMyEFnIRPy/Bywj99UCWFvDxKtIU/7kcH2C5d2TYV6fVLXZfAzRFwfdDnL5prRLHYCCjIMoMsk7h+6KrqOZmFA4bTSZdIX/DBNRwZVqx0R8eDDBTiH8oDlX22foab5Eri666dEuqfrNIO/4OYyjDr+cSbfc64xU7/YjWY3I8oRe7xg9075T8RX7poCBpMQmQErfX,iv:Cj244/8YbsSzOiGxNHTTOuGeZa6PvaO6ns5nN5NN91c=,tag:q5YStv01Yf37cUCwR3Nhjg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRThPakgvSGVSemlvRTVN
            WDcvaElQUFRTcEE4YUlZU1dyRVFmdzFvL25vCnVUZEFqMDI1MkdkSkU5RjJPTjkr
            blh0L3BjYUJjZlNTWWVMaDFHZmVVVzAKLS0tIDBtY1RoSUtPMkJFbTBQNnVrM0Zh
            b0pjMjFDeEtKL3BtV0RFR3p6ZWRJSUkKSSMF9/EEv7fQsjRWv/Frmswf3WNp9hYn
            ibOoqgn5lW/GQmr6kcgmW09s8LpJOyQM4ALM2kmnOFlv2JdK17Zdxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T23:07:01Z"
    mac: ENC[AES256_GCM,data:XSopgh+Slbfqa/OLDm79gpBtEusRr+eBgigB95ChQeH3RLCH4YpMu+SdPJkNAWDTiqOtHJPFGF/JFzg7wVqGJPa/4hAKYqV+KmeqocA8M5ODguOgYrJaQUPLu//hrFw0GTqEkxGV4eGRPTJnEeO1wxM5VmC1sJ7janGlzzUKlKg=,iv:qvhj6yoN7KHun6Mtv8G7WwTZFkBpXKK5MWBVgRM/eOc=,tag:eRt/b5/49yvVAnN5ndt4NA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
