apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:e5NeFFR3GGiSg0Y8QIlCm7XQBUGLnjz5lZYYwSHUOMpxah88bwKR7OyzLVG0F14Ml3dspiDCSj72h3zlKYXNlgJ8Z/7U5VMTvszLTafCXcz+JPmGy4u5SXPF8r31azk2eR4FMofGMrYwQfaQKdM3ledK6NoOaKzigJZ70Lvm15CzoyCSJxqaOM8FQXFDrMpDnOXlgbKSCOStZlZpv5xonBZeXIP63P4SXgXh/fnNHikQnhKsMvfmxvAfhL1wVIqHq99qHvosxnsPRliM18j/rWk6JZ16+9lhK1+2N1guASgoBYBdXEFe+62o14BuP9KL7LFdnF+Thdmu1tjTdnPc5ao0ry/HMNeQzvDHuU4RnqX351jqAdAj5MqlduS6Uk/F,iv:rzlNNwAFMxXjm8CbfNpVVYrugXsKjlQbx7C9AHs8JNs=,tag:T9p+XU33U750iVLWJLSkbQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:EXA5g0Rc78P0GhrZj3apAghZs/3ONKiy94fbVbzKNjlyYNjUZjAuWgZb05HiqzcMRxLMeXz62ApatBbXFNACVqWVohdzrtpJEotbnlC5e9ST8765wjjbRglzGS9uMnVBiSA8WpjH9X7HH4GqHvfZM3kEO+7Cym+rRFayk8/Z+kMmkTsT/0uZ3fvBi7IhiuAGzt8xlTyFRk8XtvNMRB9W8PV/S7eb41fJaskU3HWcAdTQYelvz/4xXeuMef9bjmvsVITa3uvnnGyBIM+KiA==,iv:XgCxkPJ03H2kWIAyRLGcy1uTcyAFEWDxJNa8wI7opQQ=,tag:+0I+g4+jPm4Pe8oY5Hg8CQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+bcdrpx9DvJjSKavwEeblvwKzFlmE7zvkS/N1RS8bsflj8Ck4TDWPruEcVGkf2eIcDsc3BH1EdiViXH4TtFcxYdYtMAtAj3ik4CPFl11+NeFImak5zC47Gfjo+7YqdqLdsvwzetsOtu6a4BUvM4QoZQkKZOCyC/spM+JJHXXPABSz9A4NBiIR7nBGbXx30Swmk3w4ft4IxxFAT6EsNQXrbhG57J1FiCuLjE6,iv:tzJzEHJE/dPz7tqn421SunbY2v5GVChHn0LYrNgPFCs=,tag:H4JIogilPJ1WUZXFPx5Oew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dlJ2SmpyL0FaQVh5WFdI
            SUNpeURWNkMvQm1jcGNLRzY5NkJPRVRDOURZCmN3RlpWQW5OeHp1ZW9jdHZrLytj
            dS9GaExCSzdjTHZzT1dxUmFLbHk5aUUKLS0tIHJsdW90clBRaXBzSzdzREFTVGds
            SkRsTWRRbzVkNUlLdVBRVzljQlMyT1EKfocEAKjyfu1VywqqrIpyCvch/uI2YuBm
            pKj7Zk8rhfbUWCtgSCJN9jB+EbtJJp3kArit6p1s0rcXflR0zLow3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:12:12Z"
    mac: ENC[AES256_GCM,data:9S2mar/WE3IC7DPFAdqJ8cmVUc5YGjDFK3XXsuKTqOg9e6INsQryL+uunJIh3nOnK+G969MwtETDFqyzWkgXOIBmcDvfaQ3u8qcdgRYujkq4Kg1BWV8+xdBBOq5itqxfKapdi6SCkPT20XTTSyXa0tZ9i0+3pcpYYHNmAnmgjKs=,iv:zlwAugJb2N3YurDoncs1QXc/gL4qM6Epeb13xnwiMHk=,tag:wOnyFItdsv3qi2VX5/Xduw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
