apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xpJ4lnj+4Xu9cyMR7NPviEXQe4FBw+JkKnLPfqimWJwEqZyvu3U7uAMouWK8DLeXLfx8whQpAocU2nQiZ9S+C3m68iy1CGECK7MYE8sw5n+M5o6Cct7kZNvTbYhawWK0VWnVVxU+/Rg10+DfN/EnvoNnBUa7sUzK/5dLgGC2HB1RbqR1YazctGYZ8B3tjqjvKixXeKtG2gKwDuH7CMDCl/mPdYtMpfas+Vl5vWFgRkw+VQhpxGca4srPVfWJia5WY8dPCrB+fpShkDOVQ700Dt2cVkCuFrxcM37nhmU0KgYfVryPM0GQXOzSvwq7AjPitUAfRJ7B0zULBiufKGXkGE9OnAdP81huO527jOJkv0mQfDUT5RWgtmRr9xgFCh+X,iv:fK1Qpj1VV9Fgey6PERwHCpfgNtER0UQzx5+8gqVZBBE=,tag:7wLIpgGwUUaz1sgLw0LDWg==,type:str]
    identity.pub: ENC[AES256_GCM,data:fXlo7KhmBbRTzXkDLb2SYZsLl1qerEDqzbJPM/OEFJcyPPFPFRJUfnnXckgxAmql5m/dclmm69txWmFygiPFNwN+LLzn/Z90sqYkPjCT9xyGLAgXp5QQK38eZREkLt7manZeTu6as9Ha8LNve+Xyw8fpu6fTRYCkv8DB7alOrkCfWYTkJ6hrgAwR58rfXXxbrwPaxjp6FHnU2F/Ht6Lff+LJOtCM+7L4rPvCPs5SGnELul9G1+1SAdVuS7+TlTvI90hjA3b2rGBe50viYA==,iv:mGVD6cXi56xfOteLJ/B08X2SJSH9X7tn6sxIpQ+PNMQ=,tag:aroJjGRApjfJMndFPvDO+g==,type:str]
    known_hosts: ENC[AES256_GCM,data:2K2eJU7n8gzRvYjKbPFOmX30/MMV8V8bWBdfgS2gOpkjBE2iCIWxzSVFS7rPhS2V4w+ef1Xvp8YzQ5toNtDwFzhSeq3M1OvISQd4vLRitBIXF+/AW76Y0zSqwgLBG6CNAqkkVTW5xVFUq16enzkvAfqpJZ3TW8jeZaAc4sjScf0CjZZFx2+hf40aTJCpnptQIghGvW8HHVArKowS4FSXSnogHQ3rLHOvEIku,iv:4VLnGXm1vRBrMpPGmnxw1ggzv+rqmwK7UFYR1cKYGIQ=,tag:Xc3r6BQsDLy3XIMRWBd4cA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArb0xaNmw3RXQzamxZMjc0
            OE14WFlETmcreTJHWndVLy9OT2ZDS25wemhVCkZ1bkRGVjlidXpwd2lGelFyMzNV
            Q1E1S015NFZmTXVTQ1JXallVVVhwMzgKLS0tIGwyRWdPZHBvSnZnZ1QxeTlnV1ly
            Mndzc21pN2V1dFRwdFZOb1JKYWYvV3cKFq+5X/GUN5dlFC8HG9SgcWySOzD0gkwY
            aaeLjwISiPfjLdmAUpVilkGhZO9oqA0qZCK92jjU8qMCgJdMqv++5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T12:50:34Z"
    mac: ENC[AES256_GCM,data:kL/w5RcU4GVfWLsqaz6QfgzSf/KKL7O4T6A50w8q96lfWmOqc9OH1To0oNCaaxWpY37+7PZm4VwK/ltbODoWyFAzwv5jxhKa2Q7OthJfp7oQIS48Em1p1LArUHp+kkdXdmLP6EXP6ynasN9lfLLZiO74NCMJfWQZMHlEJMJUPe8=,iv:4yG+Vz/MP7s5nNEJoaxZlrFU7Mdv47sxcop35k0QA1Q=,tag:86xfUAgUJeTnYSr2Uou52Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
