apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LyuVF4zw/fKxl3iIo6gyCbq2Eh7ruOgDhxXklyUQXhjSYanKqzHoj/C84U7zQIN0K0dJxNV56ZdlS/I0qywFZo7Oap0Wa/thI644XxxSBNiqjBWGI4tVMKIcw+9+dAQtVkg67+kkClfi1R9fNaJNuT5Tl93tSSQcxVJQ145trY15qc1Od7ijV8feDWGn2Bfrxf/suxryjPZ3leDFiaVdid8iWMFdv1XxdTJZ3yzQIzNUjtfAwEMyd8KINDJN5hpnHhPgcnUPpE61dzEmEDw5RBpZvYmi+epxX6tu/GK759N9IYM9LI0p6/Ruwdd4kXhohBrtlCF3R6Ckhdc7jE/L0BQXzsuY0UQ84MIsCj5X2kbmTlZzxUIM70bT2kH46REI,iv:Bs/7m3RX4fYHYaGjt1jAgVMgdvp1PD1+L+HEBBlhR30=,tag:h/qFMVl8gDp7qw01lbOjeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ts4hN7nC2AdH47+X53XrtJ45b39gJB8T+sqLp+7dJzkcdmCp/nLO1AGXmk3NiLycBzOs5/WdJrYc/07FuWDUrBSkBr/xtfU8qZ9SVhWIQiylqmol05F1vb9RyDMMTZd0IIt5AMJ83Q4aNt4Swd6et7nll7odOq/4mfNXiC02eFSj4Pucuf8UnjcPkyWhBrEBa/pReQme17h45HhftaObPH++5eu9t7yen6sox0s1p8zUlEg/fc1ZF6jxm37KDNaDrlc7hev/5bFk4wAUzw==,iv:26B75HU7pjFkNp+cRWzQYedcIEmZ4z1hWoBMYYQmjJM=,tag:KcuqUeoxx66AcwSYe0UnJA==,type:str]
    known_hosts: ENC[AES256_GCM,data:jo1qiF3t2WVoOiAcs6YPN4+yDUE3ZjRpKCPfYnGMd6LxBsKkibBsgqsecXG5LO7bnYSZNRD+CwycRHWUBNwNS6ZZ9/uRMITWSSAhaeyxJSCZphYDjOI8kh81vlepMnR9Hud2BQD8SMDKTed4QGHKWP1PZXPrtpVrmZ/4T8y4RdVs7+W9maGhDO1Jyt6zCHCZINVaytcC4wsUqYcP3Yq3lIcg7UMnI6gS7qMJ,iv:A48Xr4jM/4BG9fWtpWYUDNfT9Wm2Ls3P01WNvOQ+cI0=,tag:BYwMM0TlnPGpH2/RPt+cIQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN0dYa3lWWURMRlVLTCt3
            N3NkcjJKaUg1YmRqOUZOOStobDdCSFZoR2kwCks0Z3N6R2NwVmJ6V3laQjVUVXQ3
            a1A5YlNRYlE0b0xoN0FoNlNNMTcrOTgKLS0tIHhCTTh2VXp1S2NMbXZGNkVTenpt
            NlhkNE91M0JmcEJGYzVLS1BpUnlsVWcKh78ELETE5jwv1A4KP+w+EneeV5+bnV3v
            g4fWvp6UI4X/gXsuhp/suUnsFrSUUW6enI+LFX7F2eRCkuslY9bUoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:52:17Z"
    mac: ENC[AES256_GCM,data:CYqXUMpXoCtRDgLhsf4PoUEZJM/FQbSPVMJFmPACkGFh+MKZIgIgbQ+E+55SqUhib7rFRIp23ZDslQwx8eDUg6SdAWLtB8gq1zHVJjV/u20FYH49j7CKzZomjk6C1KleF/SXuTu6SZ58tmq2v8o5lOF9VDduJG8/frnATBgrtwA=,iv:S2xe51zCVo4gLLiT7jgX3SQUSsKayGGtkXyjv7P8uEo=,tag:nbzRWbhzLogJqsELa2q1Dg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
