apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:p/f++V8+p5/Uuxk23G+pEzwnC9ih6rwxd7st+akzxAwzWw+716KPlVCIzqc/mo4CxuRev/tj0OQt2HMiXnVZVdCgMPKWe7LHhyDuA3FJBNWwS/mIEudIHGYU9SJis7Rnex1TxG3eTmmzmggvHKW8yRxBexvYxW7p1nEHslCMUz61JNB9huArcVECe4MlbWN9Bp9eMucTU2jyt9HG6uc/hctjVFMEO+wJiHBA5hAEylK8m20QIy3CsZZ1xIlHoQnZhS8f1CGFD0Ec/IsVDZVKpb5hW+ZTZ6YbrTRCFMUwiOEAIbB7hVQMAsBIQMKNKpAS7cguNq7yQPcI29rLMa9qE5iF7xZ/Y132AaUqrH3pROZFgYy4yg7H5rpEFB4Mp9Ai,iv:pWMiuQCMgDyY0x2xVo2vyrgFWO63p40n90FWgAJTG4Q=,tag:Qjj4tnPPmkYtaTg7ThFlGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:PhxuqHNxwn6u3mcTSICmgWq8bClFMYUQ5dEABs/3T956NVcYkQEbGO4AGC7MVnoSIrQOL0oU0a+KJhtCjmu8yhchOA+2nTd/pzpAdoEBz7awqH0g65c4vnq+dBVX5IjhM3hHlqCOTXYI9eqauC7kdfztCri4Rh5hXReSj2L5fdhMJZV1NrJp4BD5KF8n7P5H8y8mSNPNUaz6dYIeDXqiAqdVp8btdpcJ6vZToVqnr4GEAxZxnEwWS50zmybI1pEs2Gt4uE+D3ple+FT0Ow==,iv:8J8t5qLz07L2wRSRjTnVh6xBoZs0pxQ4zOFMpJUFlI0=,tag:Vps0h0jr0s5MFw79062mdg==,type:str]
    known_hosts: ENC[AES256_GCM,data:NA6vYgk6CthMugtl7zLfvjaKxY9yLbrcdjq/o66izsyirlVO88qsk+oV2vCjSoDauUSo26rahfaALeEgEIb0Zz9lMzgO7c4zlgHzJtcKCSDd/u++IUeakqLctbGIX9tdqdLvRTMCkUWklC80PgH6NdlKfbwndPtbvvwk59uvvoHsHFZkDaww44lICI3STH0a+BPajNVZfsSvwu8pw8pUohxKawebySRME2So,iv:gdgF4/WC5sicrGWxswsCQs/9XTv68w4Zis4mScemKCY=,tag:8wt9dlKbQpsgFaXZx25AZw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1c2ztujhqrtkrgf637uzjlzjjjjd5zgfa6ut4c0zy938ae856zsfsa9ngj9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzNHWk1HZkJBWFhkb1Fh
            RHpDc1c1NjdKQTNISVhOSjBWVTY5ZkJZbVQ4ClpwY1M3SkRsWU5mYWUyUDNWM2NN
            VXh3SGh1OUVtUkVibXB5OEpwdEF1UHcKLS0tIGFMTDlkeEdhK252OCtxbE9hak1T
            VkxpVDZQdnpXbnAyVTdmcEdSU2hIRHcKLg7WUNK+/siJceJCYlY4mAFucmDYvf8m
            p2LeTIFRZOO9tVtuP2xybkEJ4Cq4o+DRiDXy2c2DBMOnO3AOM6zdDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T13:38:19Z"
    mac: ENC[AES256_GCM,data:61oCsHBQpmhP12g5cfnPum4F/czzzKMTG6Io4JCbv+M1uVlfP70EZxOMWp+5ozwHzh91D8YoZ5Ns/nK6MhTeSRFrl0GEAwHJqrpYlrpZKoU2phEqVmhv2lZxo6rkrq/YcC1W11nfYcM4blGmeijIcKZOnVrS/6MebCfdUkBxHHU=,iv:IDHh04ds5LoqvylISiiF0LG3rojLJqrcZ9cLWDbsyQY=,tag:4vKHaE9k113lc3p7KDjHEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
