apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - prowlarr/ks.yaml
  - sonarr/ks.yaml
  - jellyfin/ks.yaml
  - jellyseerr/ks.yaml
  - streamystats/ks.yaml
